libopencm3: usb_private.h File Reference
usb_private.h File Reference
Data Structures
struct _usbd_device
Internal collection of device information.
struct _usbd_device::usb_control_state
struct _usbd_device::user_control_callback
struct _usbd_driver
Enumerations
enum _usbd_transaction { USB_TRANSACTION_IN, USB_TRANSACTION_OUT, USB_TRANSACTION_SETUP }
Functions
void _usbd_control_in (usbd_device *usbd_dev, uint8_t ea)
void _usbd_control_out (usbd_device *usbd_dev, uint8_t ea)
void _usbd_control_setup (usbd_device *usbd_dev, uint8_t ea)
int _usbd_standard_request_device (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
int _usbd_standard_request_interface (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
int _usbd_standard_request_endpoint (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
int _usbd_standard_request (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
void _usbd_reset (usbd_device *usbd_dev)
Function Documentation
_usbd_control_in()
void _usbd_control_in (usbd_device * usbd_dev, uint8_t ea)
Definition at line 290 of file usb_control.c.
References usb_setup_data::bmRequestType, usb_setup_data::bRequest, _usbd_device::usb_control_state::complete, _usbd_device::control_state, _usbd_device::driver, _usbd_driver::set_address, stall_transaction(), _usbd_device::usb_control_state::state, usb_control_send_chunk(), usbd_ep_nak_set(), and usb_setup_data::wValue.
Referenced by usbd_init().
_usbd_control_out()
void _usbd_control_out (usbd_device * usbd_dev, uint8_t ea)
Definition at line 244 of file usb_control.c.
References usb_device_descriptor::bMaxPacketSize0, _usbd_device::usb_control_state::complete, _usbd_device::control_state, _usbd_device::usb_control_state::ctrl_len, _usbd_device::desc, stall_transaction(), _usbd_device::usb_control_state::state, usb_control_recv_chunk(), usb_control_request_dispatch(), usbd_ep_read_packet(), and usbd_ep_write_packet().
Referenced by usbd_init().
_usbd_control_setup()
void _usbd_control_setup (usbd_device * usbd_dev, uint8_t ea)
Definition at line 221 of file usb_control.c.
References usb_setup_data::bmRequestType, _usbd_device::usb_control_state::complete, _usbd_device::control_state, stall_transaction(), usb_control_setup_read(), usb_control_setup_write(), usbd_ep_nak_set(), usbd_ep_read_packet(), and usb_setup_data::wLength.
Referenced by usbd_init().
_usbd_standard_request()
int _usbd_standard_request (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len)
Definition at line 580 of file usb_standard.c.
References _usbd_standard_request_device(), _usbd_standard_request_endpoint(), _usbd_standard_request_interface(), and usb_setup_data::bmRequestType.
Referenced by usb_control_request_dispatch().
_usbd_standard_request_device()
int _usbd_standard_request_device (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len)
Definition at line 459 of file usb_standard.c.
References usb_setup_data::bRequest, usb_standard_device_get_status(), usb_standard_get_configuration(), usb_standard_get_descriptor(), usb_standard_set_address(), usb_standard_set_configuration(), usbd_dev, and usb_setup_data::wValue.
Referenced by _usbd_standard_request().
_usbd_standard_request_endpoint()
int _usbd_standard_request_endpoint (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len)
Definition at line 543 of file usb_standard.c.
References usb_setup_data::bRequest, usb_standard_endpoint_get_status(), usb_standard_endpoint_stall(), usb_standard_endpoint_unstall(), usbd_dev, and usb_setup_data::wValue.
Referenced by _usbd_standard_request().
_usbd_standard_request_interface()
int _usbd_standard_request_interface (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len)
Definition at line 513 of file usb_standard.c.
References usb_setup_data::bRequest, usb_standard_get_interface(), usb_standard_interface_get_status(), usb_standard_set_interface(), and usbd_dev.
Referenced by _usbd_standard_request().