libopencm3: usb_control.c File Reference
usb_control.c File Reference
Functions
static void stall_transaction (usbd_device *usbd_dev)
static bool needs_zlp (uint16_t len, uint16_t wLength, uint8_t ep_size)
If we're replying with some data, but less than the host is expecting, then we normally just do a short transfer.
int usbd_register_control_callback (usbd_device *usbd_dev, uint8_t type, uint8_t type_mask, usbd_control_callback callback)
Registers a control callback.
static void usb_control_send_chunk (usbd_device *usbd_dev)
static int usb_control_recv_chunk (usbd_device *usbd_dev)
static int usb_control_request_dispatch (usbd_device *usbd_dev, struct usb_setup_data *req)
static void usb_control_setup_read (usbd_device *usbd_dev, struct usb_setup_data *req)
static void usb_control_setup_write (usbd_device *usbd_dev, struct usb_setup_data *req)
void _usbd_control_setup (usbd_device *usbd_dev, uint8_t ea)
void _usbd_control_out (usbd_device *usbd_dev, uint8_t ea)
void _usbd_control_in (usbd_device *usbd_dev, uint8_t ea)
Function Documentation
_usbd_control_in()
void _usbd_control_in (usbd_device * usbd_dev, uint8_t ea)
Definition at line 290 of file usb_control.c.
References usb_setup_data::bmRequestType, usb_setup_data::bRequest, _usbd_device::usb_control_state::complete, _usbd_device::control_state, _usbd_device::driver, _usbd_driver::set_address, stall_transaction(), _usbd_device::usb_control_state::state, usb_control_send_chunk(), usbd_ep_nak_set(), and usb_setup_data::wValue.
Referenced by usbd_init().
_usbd_control_out()
void _usbd_control_out (usbd_device * usbd_dev, uint8_t ea)
Definition at line 244 of file usb_control.c.
References usb_device_descriptor::bMaxPacketSize0, _usbd_device::usb_control_state::complete, _usbd_device::control_state, _usbd_device::usb_control_state::ctrl_len, _usbd_device::desc, stall_transaction(), _usbd_device::usb_control_state::state, usb_control_recv_chunk(), usb_control_request_dispatch(), usbd_ep_read_packet(), and usbd_ep_write_packet().
Referenced by usbd_init().
_usbd_control_setup()
void _usbd_control_setup (usbd_device * usbd_dev, uint8_t ea)
Definition at line 221 of file usb_control.c.
References usb_setup_data::bmRequestType, _usbd_device::usb_control_state::complete, _usbd_device::control_state, stall_transaction(), usb_control_setup_read(), usb_control_setup_write(), usbd_ep_nak_set(), usbd_ep_read_packet(), and usb_setup_data::wLength.
Referenced by usbd_init().