libopencm3: usart.c File Reference
usart.c File Reference
#include <libopencm3/sam/usart.h>
#include <libopencm3/sam/pmc.h>
Functions
void usart_set_baudrate (uint32_t usart, uint32_t baud)
void usart_set_databits (uint32_t usart, int bits)
void usart_set_stopbits (uint32_t usart, enum usart_stopbits sb)
void usart_set_parity (uint32_t usart, enum usart_parity par)
void usart_set_mode (uint32_t usart, enum usart_mode mode)
void usart_set_flow_control (uint32_t usart, enum usart_flowcontrol fc)
void usart_enable (uint32_t usart)
void usart_disable (uint32_t usart)
void usart_send (uint32_t usart, uint16_t data)
uint16_t usart_recv (uint32_t usart)
void usart_wait_send_ready (uint32_t usart)
void usart_wait_recv_ready (uint32_t usart)
void usart_send_blocking (uint32_t usart, uint16_t data)
uint16_t usart_recv_blocking (uint32_t usart)
void usart_enable_rx_interrupt (uint32_t usart)
void usart_disable_rx_interrupt (uint32_t usart)
Function Documentation
usart_disable()
void usart_disable (uint32_t usart)
Definition at line 64 of file usart.c.
usart_disable_rx_interrupt()
void usart_disable_rx_interrupt (uint32_t usart)
Definition at line 107 of file usart.c.
usart_enable()
void usart_enable (uint32_t usart)
Definition at line 59 of file usart.c.
usart_enable_rx_interrupt()
void usart_enable_rx_interrupt (uint32_t usart)
Definition at line 102 of file usart.c.
usart_recv()
uint16_t usart_recv (uint32_t usart)
Definition at line 74 of file usart.c.
Referenced by usart_recv_blocking().
usart_recv_blocking()
uint16_t usart_recv_blocking (uint32_t usart)
Definition at line 95 of file usart.c.
References usart_recv(), and usart_wait_recv_ready().
usart_send()
void usart_send (uint32_t usart, uint16_t data)
Definition at line 69 of file usart.c.
Referenced by usart_send_blocking().
usart_send_blocking()
void usart_send_blocking (uint32_t usart, uint16_t data)
Definition at line 89 of file usart.c.
References usart_send(), and usart_wait_send_ready().
usart_set_baudrate()
void usart_set_baudrate (uint32_t usart, uint32_t baud)
Definition at line 23 of file usart.c.
References pmc_mck_frequency.
usart_set_databits()
void usart_set_databits (uint32_t usart, int bits)
Definition at line 28 of file usart.c.
usart_set_flow_control()
void usart_set_flow_control (uint32_t usart, enum usart_flowcontrol fc)
Definition at line 53 of file usart.c.
usart_set_mode()
void usart_set_mode (uint32_t usart, enum usart_mode mode)
Definition at line 45 of file usart.c.
usart_set_parity()
void usart_set_parity (uint32_t usart, enum usart_parity par)
Definition at line 40 of file usart.c.
usart_set_stopbits()
void usart_set_stopbits (uint32_t usart, enum usart_stopbits sb)
Definition at line 34 of file usart.c.
usart_wait_recv_ready()
void usart_wait_recv_ready (uint32_t usart)
Definition at line 84 of file usart.c.
Referenced by usart_recv_blocking().
usart_wait_send_ready()
void usart_wait_send_ready (uint32_t usart)
Definition at line 79 of file usart.c.
Referenced by usart_send_blocking().