libopencm3: I2C
I2C
STM32F2xx
libopencm3 STM32F2xx I2C
Functions
void i2c_reset (uint32_t i2c)
I2C Reset.
void i2c_peripheral_enable (uint32_t i2c)
I2C Peripheral Enable.
void i2c_peripheral_disable (uint32_t i2c)
I2C Peripheral Disable.
void i2c_send_start (uint32_t i2c)
I2C Send Start Condition.
void i2c_send_stop (uint32_t i2c)
I2C Send Stop Condition.
void i2c_clear_stop (uint32_t i2c)
I2C Clear Stop Flag.
void i2c_set_own_7bit_slave_address (uint32_t i2c, uint8_t slave)
I2C Set the 7 bit Slave Address for the Peripheral.
void i2c_set_own_10bit_slave_address (uint32_t i2c, uint16_t slave)
I2C Set the 10 bit Slave Address for the Peripheral.
void i2c_set_own_7bit_slave_address_two (uint32_t i2c, uint8_t slave)
I2C Set the secondary 7 bit Slave Address for the Peripheral.
void i2c_enable_dual_addressing_mode (uint32_t i2c)
I2C Enable dual addressing mode for the Peripheral.
void i2c_disable_dual_addressing_mode (uint32_t i2c)
I2C Disable dual addressing mode for the Peripheral.
void i2c_set_clock_frequency (uint32_t i2c, uint8_t freq)
I2C Set Peripheral Clock Frequency.
void i2c_send_data (uint32_t i2c, uint8_t data)
I2C Send Data.
void i2c_set_fast_mode (uint32_t i2c)
I2C Set Fast Mode.
void i2c_set_standard_mode (uint32_t i2c)
I2C Set Standard Mode.
void i2c_set_ccr (uint32_t i2c, uint16_t freq)
I2C Set Bus Clock Frequency.
void i2c_set_trise (uint32_t i2c, uint16_t trise)
I2C Set the Rise Time.
void i2c_send_7bit_address (uint32_t i2c, uint8_t slave, uint8_t readwrite)
I2C Send the 7-bit Slave Address.
uint8_t i2c_get_data (uint32_t i2c)
I2C Get Data.
void i2c_enable_interrupt (uint32_t i2c, uint32_t interrupt)
I2C Enable Interrupt.
void i2c_disable_interrupt (uint32_t i2c, uint32_t interrupt)
I2C Disable Interrupt.
void i2c_enable_ack (uint32_t i2c)
I2C Enable ACK.
void i2c_disable_ack (uint32_t i2c)
I2C Disable ACK.
void i2c_nack_next (uint32_t i2c)
I2C NACK Next Byte.
void i2c_nack_current (uint32_t i2c)
I2C NACK Next Byte.
void i2c_set_dutycycle (uint32_t i2c, uint32_t dutycycle)
I2C Set clock duty cycle.
void i2c_enable_dma (uint32_t i2c)
I2C Enable DMA.
void i2c_disable_dma (uint32_t i2c)
I2C Disable DMA.
void i2c_set_dma_last_transfer (uint32_t i2c)
I2C Set DMA last transfer.
void i2c_clear_dma_last_transfer (uint32_t i2c)
I2C Clear DMA last transfer.
static void i2c_write7_v1 (uint32_t i2c, int addr, uint8_t *data, size_t n)
static void i2c_read7_v1 (uint32_t i2c, int addr, uint8_t *res, size_t n)
void i2c_transfer7 (uint32_t i2c, uint8_t addr, uint8_t *w, size_t wn, uint8_t *r, size_t rn)
Run a write/read transaction to a given 7bit i2c address If both write & read are provided, the read will use repeated start.
void i2c_set_speed (uint32_t i2c, enum i2c_speeds speed, uint32_t clock_megahz)
Set the i2c communication speed.
void i2c_enable_analog_filter (uint32_t i2c)
void i2c_disable_analog_filter (uint32_t i2c)
void i2c_set_digital_filter (uint32_t i2c, uint8_t dnf_setting)
void i2c_set_prescaler (uint32_t i2c, uint8_t presc)
void i2c_set_data_setup_time (uint32_t i2c, uint8_t s_time)
void i2c_set_data_hold_time (uint32_t i2c, uint8_t h_time)
void i2c_set_scl_high_period (uint32_t i2c, uint8_t period)
void i2c_set_scl_low_period (uint32_t i2c, uint8_t period)
void i2c_enable_stretching (uint32_t i2c)
void i2c_disable_stretching (uint32_t i2c)
void i2c_set_7bit_addr_mode (uint32_t i2c)
void i2c_set_10bit_addr_mode (uint32_t i2c)
void i2c_set_7bit_address (uint32_t i2c, uint8_t addr)
void i2c_set_10bit_address (uint32_t i2c, uint16_t addr)
void i2c_set_write_transfer_dir (uint32_t i2c)
void i2c_set_read_transfer_dir (uint32_t i2c)
void i2c_set_bytes_to_transfer (uint32_t i2c, uint32_t n_bytes)
bool i2c_is_start (uint32_t i2c)
void i2c_enable_autoend (uint32_t i2c)
void i2c_disable_autoend (uint32_t i2c)
bool i2c_nack (uint32_t i2c)
bool i2c_busy (uint32_t i2c)
bool i2c_transmit_int_status (uint32_t i2c)
bool i2c_transfer_complete (uint32_t i2c)
bool i2c_received_data (uint32_t i2c)
void i2c_enable_rxdma (uint32_t i2c)
I2C Enable reception DMA.
void i2c_disable_rxdma (uint32_t i2c)
I2C Disable reception DMA.
void i2c_enable_txdma (uint32_t i2c)
I2C Enable transmission DMA.
void i2c_disable_txdma (uint32_t i2c)
I2C Disable transmission DMA.
Detailed Description
libopencm3 STM32F2xx I2C
Version
1.0.0
Date
15 October 2012
LGPL License Terms libopencm3 License
Author
© 2010 Thomas Otto tommi.nosp@m.@via.nosp@m.dmin..nosp@m.org
© 2012 Ken Sarkies ksark.nosp@m.ies@.nosp@m.inter.nosp@m.node.nosp@m..on.n.nosp@m.et
Devices can have up to three I2C peripherals. The peripherals support SMBus and PMBus variants.
A peripheral begins after reset in Slave mode. To become a Master a start condition must be generated. The peripheral will remain in Master mode unless a multimaster contention is lost or a stop condition is generated.
Function Documentation
i2c_busy()
bool i2c_busy (uint32_t i2c)
Definition at line 295 of file i2c_common_v2.c.
References I2C_ISR, and I2C_ISR_BUSY.
i2c_clear_dma_last_transfer()
void i2c_clear_dma_last_transfer (uint32_t i2c)
I2C Clear DMA last transfer.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 461 of file i2c_common_v1.c.
References I2C_CR2, and I2C_CR2_LAST.
i2c_clear_stop()
void i2c_clear_stop (uint32_t i2c)
I2C Clear Stop Flag.
Clear the "Send Stop" flag in the I2C config register
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 139 of file i2c_common_v1.c.
References I2C_CR1, I2C_CR1_STOP, I2C_ICR, and I2C_ICR_STOPCF.
i2c_disable_ack()
void i2c_disable_ack (uint32_t i2c)
I2C Disable ACK.
Disables acking of own 7/10 bit address
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 383 of file i2c_common_v1.c.
References I2C_CR1, and I2C_CR1_ACK.
Referenced by i2c_read7_v1().
i2c_disable_analog_filter()
void i2c_disable_analog_filter (uint32_t i2c)
Definition at line 186 of file i2c_common_v2.c.
References I2C_CR1, and I2C_CR1_ANFOFF.
i2c_disable_autoend()
void i2c_disable_autoend (uint32_t i2c)
Definition at line 285 of file i2c_common_v2.c.
References I2C_CR2, and I2C_CR2_AUTOEND.
Referenced by i2c_transfer7().
i2c_disable_dma()
void i2c_disable_dma (uint32_t i2c)
I2C Disable DMA.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 441 of file i2c_common_v1.c.
References I2C_CR2, and I2C_CR2_DMAEN.
i2c_disable_dual_addressing_mode()
void i2c_disable_dual_addressing_mode (uint32_t i2c)
I2C Disable dual addressing mode for the Peripheral.
Only OAR1 is recognised in 7-bit addressing mode.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 214 of file i2c_common_v1.c.
References I2C_OAR2, and I2C_OAR2_ENDUAL.
i2c_disable_interrupt()
void i2c_disable_interrupt (uint32_t i2c, uint32_t interrupt)
I2C Disable Interrupt.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] interrupt Unsigned int32. Interrupt to disable.
Definition at line 361 of file i2c_common_v1.c.
References I2C_CR1, and I2C_CR2.
i2c_disable_rxdma()
void i2c_disable_rxdma (uint32_t i2c)
I2C Disable reception DMA.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 353 of file i2c_common_v2.c.
References I2C_CR1, and I2C_CR1_RXDMAEN.
i2c_disable_stretching()
void i2c_disable_stretching (uint32_t i2c)
Definition at line 232 of file i2c_common_v2.c.
References I2C_CR1, and I2C_CR1_NOSTRETCH.
i2c_disable_txdma()
void i2c_disable_txdma (uint32_t i2c)
I2C Disable transmission DMA.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 373 of file i2c_common_v2.c.
References I2C_CR1, and I2C_CR1_TXDMAEN.
i2c_enable_ack()
void i2c_enable_ack (uint32_t i2c)
I2C Enable ACK.
Enables acking of own 7/10 bit address
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 372 of file i2c_common_v1.c.
References I2C_CR1, and I2C_CR1_ACK.
Referenced by i2c_read7_v1().
i2c_enable_analog_filter()
void i2c_enable_analog_filter (uint32_t i2c)
Definition at line 181 of file i2c_common_v2.c.
References I2C_CR1, and I2C_CR1_ANFOFF.
i2c_enable_autoend()
void i2c_enable_autoend (uint32_t i2c)
Definition at line 280 of file i2c_common_v2.c.
References I2C_CR2, and I2C_CR2_AUTOEND.
Referenced by i2c_transfer7().
i2c_enable_dma()
void i2c_enable_dma (uint32_t i2c)
I2C Enable DMA.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 431 of file i2c_common_v1.c.
References I2C_CR2, and I2C_CR2_DMAEN.
i2c_enable_dual_addressing_mode()
void i2c_enable_dual_addressing_mode (uint32_t i2c)
I2C Enable dual addressing mode for the Peripheral.
Both OAR1 and OAR2 are recognised in 7-bit addressing mode.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 201 of file i2c_common_v1.c.
References I2C_OAR2, and I2C_OAR2_ENDUAL.
i2c_enable_interrupt()
void i2c_enable_interrupt (uint32_t i2c, uint32_t interrupt)
I2C Enable Interrupt.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] interrupt Unsigned int32. Interrupt to enable.
Definition at line 350 of file i2c_common_v1.c.
References I2C_CR1, and I2C_CR2.
i2c_enable_rxdma()
void i2c_enable_rxdma (uint32_t i2c)
I2C Enable reception DMA.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 343 of file i2c_common_v2.c.
References I2C_CR1, and I2C_CR1_RXDMAEN.
i2c_enable_stretching()
void i2c_enable_stretching (uint32_t i2c)
Definition at line 227 of file i2c_common_v2.c.
References I2C_CR1, and I2C_CR1_NOSTRETCH.
i2c_enable_txdma()
void i2c_enable_txdma (uint32_t i2c)
I2C Enable transmission DMA.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 363 of file i2c_common_v2.c.
References I2C_CR1, and I2C_CR1_TXDMAEN.
i2c_get_data()
uint8_t i2c_get_data (uint32_t i2c)
I2C Get Data.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 339 of file i2c_common_v1.c.
References I2C_DR, and I2C_RXDR.
Referenced by i2c_read7_v1(), and i2c_transfer7().
i2c_is_start()
bool i2c_is_start (uint32_t i2c)
Definition at line 275 of file i2c_common_v2.c.
References I2C_CR2, and I2C_CR2_START.
i2c_nack()
bool i2c_nack (uint32_t i2c)
Definition at line 290 of file i2c_common_v2.c.
References I2C_ISR, and I2C_ISR_NACKF.
Referenced by i2c_transfer7().
i2c_nack_current()
void i2c_nack_current (uint32_t i2c)
I2C NACK Next Byte.
Causes the I2C controller to NACK the reception of the current byte
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 406 of file i2c_common_v1.c.
References I2C_CR1, and I2C_CR1_POS.
i2c_nack_next()
void i2c_nack_next (uint32_t i2c)
I2C NACK Next Byte.
Causes the I2C controller to NACK the reception of the next byte
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 394 of file i2c_common_v1.c.
References I2C_CR1, and I2C_CR1_POS.
i2c_peripheral_disable()
void i2c_peripheral_disable (uint32_t i2c)
I2C Peripheral Disable.
This must not be reset while in Master mode until a communication has finished. In Slave mode, the peripheral is disabled only after communication has ended.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 98 of file i2c_common_v1.c.
References I2C_CR1, and I2C_CR1_PE.
i2c_peripheral_enable()
void i2c_peripheral_enable (uint32_t i2c)
I2C Peripheral Enable.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 84 of file i2c_common_v1.c.
References I2C_CR1, and I2C_CR1_PE.
i2c_read7_v1()
static void i2c_read7_v1 (uint32_t i2c, int addr, uint8_t * res, size_t n) static
Definition at line 491 of file i2c_common_v1.c.
References i2c_disable_ack(), i2c_enable_ack(), i2c_get_data(), I2C_READ, i2c_send_7bit_address(), i2c_send_start(), i2c_send_stop(), I2C_SR1, I2C_SR1_ADDR, I2C_SR1_RxNE, I2C_SR1_SB, I2C_SR2, I2C_SR2_BUSY, and I2C_SR2_MSL.
Referenced by i2c_transfer7().
i2c_received_data()
bool i2c_received_data (uint32_t i2c)
Definition at line 310 of file i2c_common_v2.c.
References I2C_ISR, and I2C_ISR_RXNE.
Referenced by i2c_transfer7().
i2c_reset()
void i2c_reset (uint32_t i2c)
I2C Reset.
The I2C peripheral and all its associated configuration registers are placed in the reset condition. The reset is effected via the RCC peripheral reset system.
Parameters
[in] i2c Unsigned int32. I2C peripheral identifier I2C register base address.
Definition at line 52 of file i2c_common_v1.c.
References I2C1, I2C2, I2C3, rcc_periph_reset_pulse(), RST_I2C1, RST_I2C2, and RST_I2C3.
i2c_send_7bit_address()
void i2c_send_7bit_address (uint32_t i2c, uint8_t slave, uint8_t readwrite)
I2C Send the 7-bit Slave Address.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] slave Unsigned int16. Slave address 0...1023.
[in] readwrite Unsigned int8. Single bit to instruct slave to receive or send I2C Read/Write bit.
Definition at line 329 of file i2c_common_v1.c.
References I2C_DR.
Referenced by i2c_read7_v1(), and i2c_write7_v1().
i2c_send_data()
void i2c_send_data (uint32_t i2c, uint8_t data)
I2C Send Data.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] data Unsigned int8. Byte to send.
Definition at line 246 of file i2c_common_v1.c.
References I2C_DR, and I2C_TXDR.
Referenced by i2c_transfer7(), and i2c_write7_v1().
i2c_send_start()
void i2c_send_start (uint32_t i2c)
I2C Send Start Condition.
If in Master mode this will cause a restart condition to occur at the end of the current transmission. If in Slave mode, this will initiate a start condition when the current bus activity is completed.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 113 of file i2c_common_v1.c.
References I2C_CR1, I2C_CR1_START, I2C_CR2, and I2C_CR2_START.
Referenced by i2c_read7_v1(), i2c_transfer7(), and i2c_write7_v1().
i2c_send_stop()
void i2c_send_stop (uint32_t i2c)
I2C Send Stop Condition.
After the current byte transfer this will initiate a stop condition if in Master mode, or simply release the bus if in Slave mode.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 127 of file i2c_common_v1.c.
References I2C_CR1, I2C_CR1_STOP, I2C_CR2, and I2C_CR2_STOP.
Referenced by i2c_read7_v1(), and i2c_transfer7().
i2c_set_10bit_addr_mode()
void i2c_set_10bit_addr_mode (uint32_t i2c)
Definition at line 242 of file i2c_common_v2.c.
References I2C_CR2, and I2C_CR2_ADD10.
i2c_set_10bit_address()
void i2c_set_10bit_address (uint32_t i2c, uint16_t addr)
Definition at line 253 of file i2c_common_v2.c.
References I2C_CR2, I2C_CR2_SADD_10BIT_MASK, and I2C_CR2_SADD_10BIT_SHIFT.
i2c_set_7bit_addr_mode()
void i2c_set_7bit_addr_mode (uint32_t i2c)
Definition at line 237 of file i2c_common_v2.c.
References I2C_CR2, and I2C_CR2_ADD10.
i2c_set_7bit_address()
void i2c_set_7bit_address (uint32_t i2c, uint8_t addr)
Definition at line 247 of file i2c_common_v2.c.
References I2C_CR2, I2C_CR2_SADD_7BIT_MASK, and I2C_CR2_SADD_7BIT_SHIFT.
Referenced by i2c_transfer7().
i2c_set_bytes_to_transfer()
void i2c_set_bytes_to_transfer (uint32_t i2c, uint32_t n_bytes)
Definition at line 269 of file i2c_common_v2.c.
References I2C_CR2, I2C_CR2_NBYTES_MASK, and I2C_CR2_NBYTES_SHIFT.
Referenced by i2c_transfer7().
i2c_set_ccr()
void i2c_set_ccr (uint32_t i2c, uint16_t freq)
I2C Set Bus Clock Frequency.
Set the bus clock frequency. This is a 12 bit number (0...4095) calculated from the formulae given in the STM32F1 reference manual in the description of the CCR field. It is a divisor of the peripheral clock frequency i2c_set_clock_frequency modified by the fast mode setting i2c_set_fast_mode
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] freq Unsigned int16. Bus Clock Frequency Setting 0...4095.
Definition at line 294 of file i2c_common_v1.c.
References I2C_CCR.
Referenced by i2c_set_speed().
i2c_set_clock_frequency()
void i2c_set_clock_frequency (uint32_t i2c, uint8_t freq)
I2C Set Peripheral Clock Frequency.
Set the peripheral clock frequency: 2MHz to 36MHz (the APB frequency). Note that this is not the I2C bus clock. This is set in conjunction with the Clock Control register to generate the Master bus clock, see i2c_set_ccr
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] freq Unsigned int8. Clock Frequency Setting I2C clock frequency settings.
Definition at line 231 of file i2c_common_v1.c.
References I2C_CR2.
Referenced by i2c_set_speed().
i2c_set_data_hold_time()
void i2c_set_data_hold_time (uint32_t i2c, uint8_t h_time)
Definition at line 209 of file i2c_common_v2.c.
References I2C_TIMINGR, I2C_TIMINGR_SDADEL_MASK, and I2C_TIMINGR_SDADEL_SHIFT.
Referenced by i2c_set_speed().
i2c_set_data_setup_time()
void i2c_set_data_setup_time (uint32_t i2c, uint8_t s_time)
Definition at line 203 of file i2c_common_v2.c.
References I2C_TIMINGR, I2C_TIMINGR_SCLDEL_MASK, and I2C_TIMINGR_SCLDEL_SHIFT.
Referenced by i2c_set_speed().
i2c_set_digital_filter()
void i2c_set_digital_filter (uint32_t i2c, uint8_t dnf_setting)
Definition at line 191 of file i2c_common_v2.c.
References I2C_CR1, and I2C_CR1_DNF_MASK.
i2c_set_dma_last_transfer()
void i2c_set_dma_last_transfer (uint32_t i2c)
I2C Set DMA last transfer.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 451 of file i2c_common_v1.c.
References I2C_CR2, and I2C_CR2_LAST.
i2c_set_dutycycle()
void i2c_set_dutycycle (uint32_t i2c, uint32_t dutycycle)
I2C Set clock duty cycle.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] dutycycle Unsigned int32. I2C duty cycle I2C peripheral clock duty cycles.
Definition at line 417 of file i2c_common_v1.c.
References I2C_CCR, I2C_CCR_DUTY, and I2C_CCR_DUTY_DIV2.
i2c_set_fast_mode()
void i2c_set_fast_mode (uint32_t i2c)
I2C Set Fast Mode.
Set the clock frequency to the high clock rate mode (up to 400kHz). The actual clock frequency must be set with i2c_set_clock_frequency
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 260 of file i2c_common_v1.c.
References I2C_CCR, and I2C_CCR_FS.
Referenced by i2c_set_speed().
i2c_set_own_10bit_slave_address()
void i2c_set_own_10bit_slave_address (uint32_t i2c, uint16_t slave)
I2C Set the 10 bit Slave Address for the Peripheral.
This sets an address for Slave mode operation, in 10 bit form.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] slave Unsigned int16. Slave address 0...1023.
This sets an address for Slave mode operation, in 10 bit form.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] slave Unsigned int16. Slave address 0...1023.
Definition at line 172 of file i2c_common_v1.c.
References I2C_OAR1, I2C_OAR1_ADDMODE, and I2C_OAR1_OA1MODE.
i2c_set_own_7bit_slave_address()
void i2c_set_own_7bit_slave_address (uint32_t i2c, uint8_t slave)
I2C Set the 7 bit Slave Address for the Peripheral.
This sets an address for Slave mode operation, in 7 bit form.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] slave Unsigned int8. Slave address 0...127.
Definition at line 153 of file i2c_common_v1.c.
References I2C_OAR1, and I2C_OAR1_OA1MODE.
i2c_set_own_7bit_slave_address_two()
void i2c_set_own_7bit_slave_address_two (uint32_t i2c, uint8_t slave)
I2C Set the secondary 7 bit Slave Address for the Peripheral.
This sets a secondary address for Slave mode operation, in 7 bit form.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] slave Unsigned int8. Slave address 0...127.
Definition at line 187 of file i2c_common_v1.c.
References I2C_OAR2.
i2c_set_prescaler()
void i2c_set_prescaler (uint32_t i2c, uint8_t presc)
Definition at line 197 of file i2c_common_v2.c.
References I2C_TIMINGR, I2C_TIMINGR_PRESC_MASK, and I2C_TIMINGR_PRESC_SHIFT.
Referenced by i2c_set_speed().
i2c_set_read_transfer_dir()
void i2c_set_read_transfer_dir (uint32_t i2c)
Definition at line 264 of file i2c_common_v2.c.
References I2C_CR2, and I2C_CR2_RD_WRN.
Referenced by i2c_transfer7().
i2c_set_scl_high_period()
void i2c_set_scl_high_period (uint32_t i2c, uint8_t period)
Definition at line 215 of file i2c_common_v2.c.
References I2C_TIMINGR, I2C_TIMINGR_SCLH_MASK, and I2C_TIMINGR_SCLH_SHIFT.
Referenced by i2c_set_speed().
i2c_set_scl_low_period()
void i2c_set_scl_low_period (uint32_t i2c, uint8_t period)
Definition at line 221 of file i2c_common_v2.c.
References I2C_TIMINGR, I2C_TIMINGR_SCLL_MASK, and I2C_TIMINGR_SCLL_SHIFT.
Referenced by i2c_set_speed().
i2c_set_speed()
void i2c_set_speed (uint32_t i2c, enum i2c_speeds speed, uint32_t clock_megahz)
Set the i2c communication speed.
Parameters
i2c peripheral, eg I2C1
speed one of the listed speed modes i2c_speeds
clock_megahz i2c peripheral clock speed in MHz. Usually, rcc_apb1_frequency / 1e6
NOTE: 1MHz mode not yet implemented! Min clock speed: 8MHz for FM, 2Mhz for SM,
Parameters
i2c peripheral, eg I2C1
speed one of the listed speed modes i2c_speeds
clock_megahz i2c peripheral clock speed in MHz. Usually, rcc_apb1_frequency / 1e6
Definition at line 548 of file i2c_common_v1.c.
References i2c_set_ccr(), i2c_set_clock_frequency(), i2c_set_data_hold_time(), i2c_set_data_setup_time(), i2c_set_fast_mode(), i2c_set_prescaler(), i2c_set_scl_high_period(), i2c_set_scl_low_period(), i2c_set_standard_mode(), i2c_set_trise(), i2c_speed_fm_400k, i2c_speed_fmp_1m, and i2c_speed_sm_100k.
i2c_set_standard_mode()
void i2c_set_standard_mode (uint32_t i2c)
I2C Set Standard Mode.
Set the clock frequency to the standard clock rate mode (up to 100kHz). The actual clock frequency must be set with i2c_set_clock_frequency
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 274 of file i2c_common_v1.c.
References I2C_CCR, and I2C_CCR_FS.
Referenced by i2c_set_speed().
i2c_set_trise()
void i2c_set_trise (uint32_t i2c, uint16_t trise)
I2C Set the Rise Time.
Set the maximum rise time on the bus according to the I2C specification, as 1 more than the specified rise time in peripheral clock cycles. This is a 6 bit number.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] trise Unsigned int16. Rise Time Setting 0...63.
Definition at line 315 of file i2c_common_v1.c.
References I2C_TRISE.
Referenced by i2c_set_speed().
i2c_set_write_transfer_dir()
void i2c_set_write_transfer_dir (uint32_t i2c)
Definition at line 259 of file i2c_common_v2.c.
References I2C_CR2, and I2C_CR2_RD_WRN.
Referenced by i2c_transfer7().
i2c_transfer7()
void i2c_transfer7 (uint32_t i2c, uint8_t addr, uint8_t * w, size_t wn, uint8_t * r, size_t rn)
Run a write/read transaction to a given 7bit i2c address If both write & read are provided, the read will use repeated start.
Both write and read are optional There are likely still issues with repeated start/stop condtions!
Parameters
i2c peripheral of choice, eg I2C1
addr 7 bit i2c device address
w buffer of data to write
wn length of w
r destination buffer to read into
rn number of bytes to read (r should be at least this long)
Both write and read are optional
Parameters
i2c peripheral of choice, eg I2C1
addr 7 bit i2c device address
w buffer of data to write
wn length of w
r destination buffer to read into
rn number of bytes to read (r should be at least this long)
Definition at line 531 of file i2c_common_v1.c.
References i2c_disable_autoend(), i2c_enable_autoend(), i2c_get_data(), i2c_nack(), i2c_read7_v1(), i2c_received_data(), i2c_send_data(), i2c_send_start(), i2c_send_stop(), i2c_set_7bit_address(), i2c_set_bytes_to_transfer(), i2c_set_read_transfer_dir(), i2c_set_write_transfer_dir(), i2c_transfer_complete(), i2c_transmit_int_status(), and i2c_write7_v1().
i2c_transfer_complete()
bool i2c_transfer_complete (uint32_t i2c)
Definition at line 305 of file i2c_common_v2.c.
References I2C_ISR, and I2C_ISR_TC.
Referenced by i2c_transfer7().
i2c_transmit_int_status()
bool i2c_transmit_int_status (uint32_t i2c)
Definition at line 300 of file i2c_common_v2.c.
References I2C_ISR, and I2C_ISR_TXIS.
Referenced by i2c_transfer7().
i2c_write7_v1()
static void i2c_write7_v1 (uint32_t i2c, int addr, uint8_t * data, size_t n) static
Definition at line 466 of file i2c_common_v1.c.
References i2c_send_7bit_address(), i2c_send_data(), i2c_send_start(), I2C_SR1, I2C_SR1_ADDR, I2C_SR1_BTF, I2C_SR1_SB, I2C_SR2, I2C_SR2_BUSY, I2C_SR2_MSL, and I2C_WRITE.
Referenced by i2c_transfer7().