libopencm3: RCC Defines
RCC Defines
STM32F7xx Defines
Defined Constants and Types for the STM32F7xx Reset and Clock Control
Functions
void rcc_peripheral_enable_clock (volatile uint32_t *reg, uint32_t en)
RCC Enable Peripheral Clocks.
void rcc_peripheral_disable_clock (volatile uint32_t *reg, uint32_t en)
RCC Disable Peripheral Clocks.
void rcc_peripheral_reset (volatile uint32_t *reg, uint32_t reset)
RCC Reset Peripherals.
void rcc_peripheral_clear_reset (volatile uint32_t *reg, uint32_t clear_reset)
RCC Remove Reset on Peripherals.
void rcc_periph_clock_enable (enum rcc_periph_clken clken)
Enable Peripheral Clock in running mode.
void rcc_periph_clock_disable (enum rcc_periph_clken clken)
Disable Peripheral Clock in running mode.
void rcc_periph_reset_pulse (enum rcc_periph_rst rst)
Reset Peripheral, pulsed.
void rcc_periph_reset_hold (enum rcc_periph_rst rst)
Reset Peripheral, hold.
void rcc_periph_reset_release (enum rcc_periph_rst rst)
Reset Peripheral, release.
void rcc_set_mco (uint32_t mcosrc)
Select the source of Microcontroller Clock Output.
void rcc_osc_bypass_enable (enum rcc_osc osc)
RCC Enable Bypass.
void rcc_osc_bypass_disable (enum rcc_osc osc)
RCC Disable Bypass.
bool rcc_is_osc_ready (enum rcc_osc osc)
Is the given oscillator ready?
void rcc_wait_for_osc_ready (enum rcc_osc osc)
Wait for Oscillator Ready.
Detailed Description
Defined Constants and Types for the STM32F7xx Reset and Clock Control
Version
1.0.0
Author
© 2015 Karl Palsson karlp.nosp@m.@twe.nosp@m.ak.ne.nosp@m.t.au
Date
October, 2015
LGPL License Terms libopencm3 License
Author
© 2013 Frantisek Burian BuFra.nosp@m.n@se.nosp@m.znam..nosp@m.cz
Function Documentation
rcc_is_osc_ready()
bool rcc_is_osc_ready (enum rcc_osc osc)
Is the given oscillator ready?
Parameters
osc Oscillator ID
Returns
true if the hardware indicates the oscillator is ready.
rcc_osc_bypass_disable()
void rcc_osc_bypass_disable (enum rcc_osc osc)
RCC Disable Bypass.
Re-enable the internal clock (high speed and low speed clocks only). The internal clock must be disabled (see rcc_osc_off) for this to have effect.
Note
The LSE clock is in the backup domain and cannot have bypass removed until the backup domain write protection has been removed (see pwr_disable_backup_domain_write_protect) or the backup domain has been reset (see rcc_backupdomain_reset).
Parameters
[in] osc Oscillator ID. Only HSE and LSE have effect.
Definition at line 241 of file rcc_common_all.c.
References RCC_BDCR, RCC_BDCR_LSEBYP, RCC_CR, RCC_CR_HSEBYP, RCC_CSR, RCC_HSE, and RCC_LSE.
rcc_osc_bypass_enable()
void rcc_osc_bypass_enable (enum rcc_osc osc)
RCC Enable Bypass.
Enable an external clock to bypass the internal clock (high speed and low speed clocks only). The external clock must be enabled (see rcc_osc_on) and the internal clock must be disabled (see rcc_osc_off) for this to have effect.
Note
The LSE clock is in the backup domain and cannot be bypassed until the backup domain write protection has been removed (see pwr_disable_backup_domain_write_protect).
Parameters
[in] osc Oscillator ID. Only HSE and LSE have effect.
Definition at line 211 of file rcc_common_all.c.
References RCC_BDCR, RCC_BDCR_LSEBYP, RCC_CR, RCC_CR_HSEBYP, RCC_CSR, RCC_HSE, and RCC_LSE.
rcc_periph_clock_disable()
void rcc_periph_clock_disable (enum rcc_periph_clken clken)
Disable Peripheral Clock in running mode.
Disable the clock on particular peripheral.
Parameters
[in] clken rcc_periph_clken Peripheral RCC
For available constants, see rcc_periph_clken (RCC_UART1 for example)
Definition at line 135 of file rcc_common_all.c.
References _RCC_BIT, and _RCC_REG.
rcc_periph_clock_enable()
void rcc_periph_clock_enable (enum rcc_periph_clken clken)
Enable Peripheral Clock in running mode.
Enable the clock on particular peripheral.
Parameters
[in] clken rcc_periph_clken Peripheral RCC
For available constants, see rcc_periph_clken (RCC_UART1 for example)
Definition at line 121 of file rcc_common_all.c.
References _RCC_BIT, and _RCC_REG.
Referenced by crs_autotrim_usb_enable(), and rcc_clock_setup_hse_3v3().
rcc_periph_reset_hold()
void rcc_periph_reset_hold (enum rcc_periph_rst rst)
Reset Peripheral, hold.
Reset particular peripheral, and hold in reset state.
Parameters
[in] rst rcc_periph_rst Peripheral reset
For available constants, see rcc_periph_rst (RST_UART1 for example)
Definition at line 166 of file rcc_common_all.c.
References _RCC_BIT, and _RCC_REG.
rcc_periph_reset_pulse()
void rcc_periph_reset_pulse (enum rcc_periph_rst rst)
Reset Peripheral, pulsed.
Reset particular peripheral, and restore to working state.
Parameters
[in] rst rcc_periph_rst Peripheral reset
For available constants, see rcc_periph_rst (RST_UART1 for example)
Definition at line 150 of file rcc_common_all.c.
References _RCC_BIT, and _RCC_REG.
Referenced by i2c_reset(), spi_reset(), and timer_reset().
rcc_periph_reset_release()
void rcc_periph_reset_release (enum rcc_periph_rst rst)
Reset Peripheral, release.
Restore peripheral from reset state to working state.
Parameters
[in] rst rcc_periph_rst Peripheral reset
For available constants, see rcc_periph_rst (RST_UART1 for example)
Definition at line 181 of file rcc_common_all.c.
References _RCC_BIT, and _RCC_REG.
rcc_peripheral_clear_reset()
void rcc_peripheral_clear_reset (volatile uint32_t * reg, uint32_t clear_reset)
RCC Remove Reset on Peripherals.
Remove the reset on particular peripherals. There are three registers involved, each one controlling reset of peripherals associated with the AHB, APB1 and APB2 respectively. Several peripherals could have the reset removed simultaneously only if they are controlled by the same register.
Parameters
[in] *reg Unsigned int32. Pointer to a Reset Register (either RCC_AHBENR, RCC_APB1ENR or RCC_APB2ENR)
[in] clear_reset Unsigned int32. Logical OR of all resets to be removed:
If register is RCC_AHBRSTR, from rcc_ahbrstr_rst
If register is RCC_APB1RSTR, from rcc_apb1rstr_rst
If register is RCC_APB2RSTR, from rcc_apb2rstr_rst
Definition at line 103 of file rcc_common_all.c.
rcc_peripheral_disable_clock()
void rcc_peripheral_disable_clock (volatile uint32_t * reg, uint32_t en)
RCC Disable Peripheral Clocks.
Enable the clock on particular peripherals. There are three registers involved, each one controlling the enabling of clocks associated with the AHB, APB1 and APB2 respectively. Several peripherals could be disabled simultaneously only if they are controlled by the same register.
Parameters
[in] *reg Unsigned int32. Pointer to a Clock Enable Register (either RCC_AHBENR, RCC_APB1ENR or RCC_APB2ENR)
[in] en Unsigned int32. Logical OR of all enables to be used for disabling.
If register is RCC_AHBER, from rcc_ahbenr_en
If register is RCC_APB1ENR, from rcc_apb1enr_en
If register is RCC_APB2ENR, from rcc_apb2enr_en
Definition at line 62 of file rcc_common_all.c.
rcc_peripheral_enable_clock()
void rcc_peripheral_enable_clock (volatile uint32_t * reg, uint32_t en)
RCC Enable Peripheral Clocks.
Enable the clock on particular peripherals. There are three registers involved, each one controlling the enabling of clocks associated with the AHB, APB1 and APB2 respectively. Several peripherals could be enabled simultaneously only if they are controlled by the same register.
Parameters
[in] *reg Unsigned int32. Pointer to a Clock Enable Register (either RCC_AHBENR, RCC_APB1ENR or RCC_APB2ENR)
[in] en Unsigned int32. Logical OR of all enables to be set
If register is RCC_AHBER, from rcc_ahbenr_en
If register is RCC_APB1ENR, from rcc_apb1enr_en
If register is RCC_APB2ENR, from rcc_apb2enr_en
Definition at line 41 of file rcc_common_all.c.
rcc_peripheral_reset()
void rcc_peripheral_reset (volatile uint32_t * reg, uint32_t reset)
RCC Reset Peripherals.
Reset particular peripherals. There are three registers involved, each one controlling reset of peripherals associated with the AHB, APB1 and APB2 respectively. Several peripherals could be reset simultaneously only if they are controlled by the same register.
Parameters
[in] *reg Unsigned int32. Pointer to a Reset Register (either RCC_AHBENR, RCC_APB1ENR or RCC_APB2ENR)
[in] reset Unsigned int32. Logical OR of all resets.
If register is RCC_AHBRSTR, from rcc_ahbrstr_rst
If register is RCC_APB1RSTR, from rcc_apb1rstr_rst
If register is RCC_APB2RSTR, from rcc_apb2rstr_rst
Definition at line 82 of file rcc_common_all.c.
rcc_set_mco()
void rcc_set_mco (uint32_t mcosrc)
Select the source of Microcontroller Clock Output.
Exact sources available depend on your target. On devices with multiple MCO pins, this function controls MCO1
[in] mcosrc the unshifted source bits
Definition at line 194 of file rcc_common_all.c.
References RCC_CFGR, RCC_CFGR_MCO_MASK, and RCC_CFGR_MCO_SHIFT.
rcc_wait_for_osc_ready()
void rcc_wait_for_osc_ready (enum rcc_osc osc)
Wait for Oscillator Ready.
Block until the hardware indicates that the Oscillator is ready.
Parameters
osc Oscillator ID
Definition at line 124 of file rcc.c.
References RCC_BDCR, RCC_BDCR_LSERDY, RCC_CR, RCC_CR_HSERDY, RCC_CR_HSIRDY, RCC_CR_PLLRDY, RCC_CSR, RCC_CSR_LSIRDY, RCC_HSE, RCC_HSI, RCC_LSE, RCC_LSI, and RCC_PLL.
Referenced by rcc_clock_setup_hse_3v3().