libopencm3: rcc.c File Reference
rcc.c File Reference
#include <libopencm3/cm3/assert.h>
#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/pwr.h>
#include <libopencm3/stm32/flash.h>
Functions
void rcc_osc_ready_int_clear (enum rcc_osc osc)
void rcc_osc_ready_int_enable (enum rcc_osc osc)
void rcc_osc_ready_int_disable (enum rcc_osc osc)
int rcc_osc_ready_int_flag (enum rcc_osc osc)
void rcc_css_int_clear (void)
int rcc_css_int_flag (void)
void rcc_wait_for_osc_ready (enum rcc_osc osc)
Wait for Oscillator Ready.
void rcc_wait_for_sysclk_status (enum rcc_osc osc)
void rcc_osc_on (enum rcc_osc osc)
void rcc_osc_off (enum rcc_osc osc)
void rcc_css_enable (void)
void rcc_css_disable (void)
void rcc_set_sysclk_source (uint32_t clk)
void rcc_set_pll_source (uint32_t pllsrc)
void rcc_set_ppre2 (uint32_t ppre2)
void rcc_set_ppre1 (uint32_t ppre1)
void rcc_set_hpre (uint32_t hpre)
void rcc_set_rtcpre (uint32_t rtcpre)
void rcc_set_main_pll_hsi (uint32_t pllm, uint32_t plln, uint32_t pllp, uint32_t pllq)
void rcc_set_main_pll_hse (uint32_t pllm, uint32_t plln, uint32_t pllp, uint32_t pllq)
uint32_t rcc_system_clock_source (void)
void rcc_clock_setup_hse_3v3 (const struct rcc_clock_scale *clock)
Variables
uint32_t rcc_ahb_frequency = 16000000
uint32_t rcc_apb1_frequency = 16000000
uint32_t rcc_apb2_frequency = 16000000
const struct rcc_clock_scale rcc_hse_25mhz_3v3 [RCC_CLOCK_3V3_END]
Function Documentation
rcc_clock_setup_hse_3v3()
void rcc_clock_setup_hse_3v3 (const struct rcc_clock_scale * clock)
Definition at line 295 of file rcc.c.
References rcc_clock_scale::apb1_frequency, rcc_clock_scale::apb2_frequency, rcc_clock_scale::flash_config, flash_set_ws(), rcc_clock_scale::hpre, rcc_clock_scale::overdrive, rcc_clock_scale::pllm, rcc_clock_scale::plln, rcc_clock_scale::pllp, rcc_clock_scale::pllq, rcc_clock_scale::ppre1, rcc_clock_scale::ppre2, pwr_enable_overdrive(), pwr_set_vos_scale(), rcc_apb1_frequency, rcc_apb2_frequency, RCC_CFGR_SW_HSI, RCC_CFGR_SW_PLL, RCC_HSE, RCC_HSI, rcc_osc_off(), rcc_osc_on(), rcc_periph_clock_enable(), RCC_PLL, RCC_PWR, rcc_set_hpre(), rcc_set_main_pll_hse(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), rcc_wait_for_osc_ready(), rcc_wait_for_sysclk_status(), and rcc_clock_scale::vos_scale.
rcc_css_disable()
void rcc_css_disable (void)
Definition at line 210 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
rcc_css_enable()
void rcc_css_enable (void)
Definition at line 205 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
rcc_css_int_clear()
void rcc_css_int_clear (void)
Definition at line 114 of file rcc.c.
References RCC_CIR, and RCC_CIR_CSSC.
rcc_css_int_flag()
int rcc_css_int_flag (void)
Definition at line 119 of file rcc.c.
References RCC_CIR, and RCC_CIR_CSSF.
rcc_osc_off()
void rcc_osc_off (enum rcc_osc osc)
Definition at line 184 of file rcc.c.
References RCC_BDCR, RCC_BDCR_LSEON, RCC_CR, RCC_CR_HSEON, RCC_CR_HSION, RCC_CR_PLLON, RCC_CSR, RCC_CSR_LSION, RCC_HSE, RCC_HSI, RCC_LSE, RCC_LSI, and RCC_PLL.
Referenced by rcc_clock_setup_hse_3v3().
rcc_osc_on()
void rcc_osc_on (enum rcc_osc osc)
Definition at line 163 of file rcc.c.
References RCC_BDCR, RCC_BDCR_LSEON, RCC_CR, RCC_CR_HSEON, RCC_CR_HSION, RCC_CR_PLLON, RCC_CSR, RCC_CSR_LSION, RCC_HSE, RCC_HSI, RCC_LSE, RCC_LSI, and RCC_PLL.
Referenced by rcc_clock_setup_hse_3v3().
rcc_osc_ready_int_clear()
void rcc_osc_ready_int_clear (enum rcc_osc osc)
Definition at line 28 of file rcc.c.
References RCC_CIR, RCC_CIR_HSERDYC, RCC_CIR_HSIRDYC, RCC_CIR_LSERDYC, RCC_CIR_LSIRDYC, RCC_CIR_PLLRDYC, RCC_HSE, RCC_HSI, RCC_LSE, RCC_LSI, and RCC_PLL.
rcc_osc_ready_int_disable()
void rcc_osc_ready_int_disable (enum rcc_osc osc)
Definition at line 70 of file rcc.c.
References RCC_CIR, RCC_CIR_HSERDYIE, RCC_CIR_HSIRDYIE, RCC_CIR_LSERDYIE, RCC_CIR_LSIRDYIE, RCC_CIR_PLLRDYIE, RCC_HSE, RCC_HSI, RCC_LSE, RCC_LSI, and RCC_PLL.
rcc_osc_ready_int_enable()
void rcc_osc_ready_int_enable (enum rcc_osc osc)
Definition at line 49 of file rcc.c.
References RCC_CIR, RCC_CIR_HSERDYIE, RCC_CIR_HSIRDYIE, RCC_CIR_LSERDYIE, RCC_CIR_LSIRDYIE, RCC_CIR_PLLRDYIE, RCC_HSE, RCC_HSI, RCC_LSE, RCC_LSI, and RCC_PLL.
rcc_osc_ready_int_flag()
int rcc_osc_ready_int_flag (enum rcc_osc osc)
Definition at line 91 of file rcc.c.
References RCC_CIR, RCC_CIR_HSERDYF, RCC_CIR_HSIRDYF, RCC_CIR_LSERDYF, RCC_CIR_LSIRDYF, RCC_CIR_PLLRDYF, RCC_HSE, RCC_HSI, RCC_LSE, RCC_LSI, and RCC_PLL.
rcc_set_hpre()
void rcc_set_hpre (uint32_t hpre)
Definition at line 251 of file rcc.c.
References RCC_CFGR, RCC_CFGR_HPRE_MASK, and RCC_CFGR_HPRE_SHIFT.
Referenced by rcc_clock_setup_hse_3v3().
rcc_set_main_pll_hse()
void rcc_set_main_pll_hse (uint32_t pllm, uint32_t plln, uint32_t pllp, uint32_t pllq)
Definition at line 278 of file rcc.c.
References RCC_PLLCFGR, RCC_PLLCFGR_PLLM_SHIFT, RCC_PLLCFGR_PLLN_SHIFT, RCC_PLLCFGR_PLLP_SHIFT, RCC_PLLCFGR_PLLQ_SHIFT, and RCC_PLLCFGR_PLLSRC.
Referenced by rcc_clock_setup_hse_3v3().
rcc_set_main_pll_hsi()
void rcc_set_main_pll_hsi (uint32_t pllm, uint32_t plln, uint32_t pllp, uint32_t pllq)
Definition at line 269 of file rcc.c.
References RCC_PLLCFGR, RCC_PLLCFGR_PLLM_SHIFT, RCC_PLLCFGR_PLLN_SHIFT, RCC_PLLCFGR_PLLP_SHIFT, and RCC_PLLCFGR_PLLQ_SHIFT.
rcc_set_pll_source()
void rcc_set_pll_source (uint32_t pllsrc)
Definition at line 224 of file rcc.c.
References RCC_PLLCFGR.
rcc_set_ppre1()
void rcc_set_ppre1 (uint32_t ppre1)
Definition at line 242 of file rcc.c.
References RCC_CFGR, RCC_CFGR_PPRE1_MASK, and RCC_CFGR_PPRE1_SHIFT.
Referenced by rcc_clock_setup_hse_3v3().
rcc_set_ppre2()
void rcc_set_ppre2 (uint32_t ppre2)
Definition at line 233 of file rcc.c.
References RCC_CFGR, RCC_CFGR_PPRE2_MASK, and RCC_CFGR_PPRE2_SHIFT.
Referenced by rcc_clock_setup_hse_3v3().
rcc_set_rtcpre()
void rcc_set_rtcpre (uint32_t rtcpre)
Definition at line 260 of file rcc.c.
References RCC_CFGR, RCC_CFGR_RTCPRE_MASK, and RCC_CFGR_RTCPRE_SHIFT.
rcc_set_sysclk_source()
void rcc_set_sysclk_source (uint32_t clk)
Definition at line 215 of file rcc.c.
References RCC_CFGR, RCC_CFGR_SW_MASK, and RCC_CFGR_SW_SHIFT.
Referenced by rcc_clock_setup_hse_3v3().
rcc_system_clock_source()
uint32_t rcc_system_clock_source (void)
Definition at line 288 of file rcc.c.
References RCC_CFGR, RCC_CFGR_SWS_MASK, and RCC_CFGR_SWS_SHIFT.
rcc_wait_for_sysclk_status()
void rcc_wait_for_sysclk_status (enum rcc_osc osc)
Definition at line 145 of file rcc.c.
References RCC_CFGR, RCC_CFGR_SWS_HSE, RCC_CFGR_SWS_HSI, RCC_CFGR_SWS_PLL, RCC_HSE, RCC_HSI, and RCC_PLL.
Referenced by rcc_clock_setup_hse_3v3().
Variable Documentation
rcc_ahb_frequency
uint32_t rcc_ahb_frequency = 16000000
Definition at line 6 of file rcc.c.
rcc_apb1_frequency
uint32_t rcc_apb1_frequency = 16000000
Definition at line 7 of file rcc.c.
Referenced by rcc_clock_setup_hse_3v3(), and usart_set_baudrate().
rcc_apb2_frequency
uint32_t rcc_apb2_frequency = 16000000
Definition at line 8 of file rcc.c.
Referenced by rcc_clock_setup_hse_3v3(), and usart_set_baudrate().
rcc_hse_25mhz_3v3
const struct rcc_clock_scale rcc_hse_25mhz_3v3[RCC_CLOCK_3V3_END]
Initial value:
= {
        {
                .pllm = 25,
                .plln = 432,
                .pllp = 2,
                .pllq = 9,
                .flash_config = FLASH_ACR_ICEN | FLASH_ACR_DCEN |
                                FLASH_ACR_LATENCY_7WS,
                .hpre = RCC_CFGR_HPRE_DIV_NONE,
                .ppre1 = RCC_CFGR_PPRE_DIV_4,
                .ppre2 = RCC_CFGR_PPRE_DIV_2,
                .vos_scale = PWR_SCALE1,
                .overdrive = 1,
                .apb1_frequency = 108000000,
                .apb2_frequency = 216000000,
        },
}
Definition at line 10 of file rcc.c.