libopencm3: RCC
RCC
STM32L0xx
libopencm3 STM32L0xx Reset and Clock Control
Functions
void rcc_osc_on (enum rcc_osc osc)
void rcc_osc_off (enum rcc_osc osc)
void rcc_osc_ready_int_clear (enum rcc_osc osc)
RCC Clear the Oscillator Ready Interrupt Flag.
void rcc_osc_ready_int_enable (enum rcc_osc osc)
RCC Enable the Oscillator Ready Interrupt.
void rcc_osc_ready_int_disable (enum rcc_osc osc)
RCC Disable the Oscillator Ready Interrupt.
int rcc_osc_ready_int_flag (enum rcc_osc osc)
RCC Read the Oscillator Ready Interrupt Flag.
bool rcc_is_osc_ready (enum rcc_osc osc)
Is the given oscillator ready?
void rcc_wait_for_osc_ready (enum rcc_osc osc)
Wait for Oscillator Ready.
void rcc_set_hsi48_source_rc48 (void)
RCC Set HSI48 clock source to the RC48 (CRS)
void rcc_set_hsi48_source_pll (void)
RCC Set HSI48 clock source to the PLL.
void rcc_set_sysclk_source (enum rcc_osc osc)
RCC Set the Source for the System Clock.
void rcc_set_pll_multiplier (uint32_t factor)
RCC Set the PLL Multiplication Factor.
void rcc_set_pll_divider (uint32_t factor)
RCC Set the PLL Division Factor.
void rcc_set_ppre1 (uint32_t ppre)
RCC Set the APB1 Prescale Factor.
void rcc_set_ppre2 (uint32_t ppre)
RCC Set the APB2 Prescale Factor.
void rcc_set_hpre (uint32_t hpre)
RCC Set the AHB Prescale Factor.
void rcc_clock_setup_pll (const struct rcc_clock_scale *clock)
Set up sysclock with PLL from HSI16.
Variables
uint32_t rcc_ahb_frequency = 2097000
uint32_t rcc_apb1_frequency = 2097000
uint32_t rcc_apb2_frequency = 2097000
Detailed Description
libopencm3 STM32L0xx Reset and Clock Control
Version
1.0.0
Date
November 2014
This library supports the Reset and Clock Control System in the STM32F0xx series of ARM Cortex Microcontrollers by ST Microelectronics.
LGPL License Terms libopencm3 License
Function Documentation
rcc_clock_setup_pll()
void rcc_clock_setup_pll (const struct rcc_clock_scale * clock)
Set up sysclock with PLL from HSI16.
Parameters
clock full struct with desired parameters
Definition at line 385 of file rcc.c.
References rcc_clock_scale::ahb_frequency, rcc_clock_scale::apb1_frequency, rcc_clock_scale::apb2_frequency, flash_prefetch_enable(), flash_set_ws(), rcc_clock_scale::flash_waitstates, rcc_clock_scale::hpre, rcc_clock_scale::pll_div, rcc_clock_scale::pll_mul, rcc_clock_scale::pll_source, rcc_clock_scale::ppre1, rcc_clock_scale::ppre2, pwr_set_vos_scale(), rcc_ahb_frequency, rcc_apb1_frequency, rcc_apb2_frequency, RCC_CFGR_PLLSRC_HSE_CLK, RCC_HSE, RCC_HSI16, rcc_is_osc_ready(), rcc_osc_off(), rcc_osc_on(), rcc_periph_clock_enable(), RCC_PLL, RCC_PWR, rcc_set_hpre(), rcc_set_pll_divider(), rcc_set_pll_multiplier(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), rcc_wait_for_osc_ready(), and rcc_clock_scale::voltage_scale.
rcc_is_osc_ready()
bool rcc_is_osc_ready (enum rcc_osc osc)
Is the given oscillator ready?
Parameters
osc Oscillator ID
Returns
true if the hardware indicates the oscillator is ready.
Definition at line 237 of file rcc.c.
References RCC_CR, RCC_CR_HSERDY, RCC_CR_HSI16RDY, RCC_CR_MSIRDY, RCC_CR_PLLRDY, RCC_CRRCR, RCC_CRRCR_HSI48RDY, RCC_CSR, RCC_CSR_LSERDY, RCC_CSR_LSIRDY, RCC_HSE, RCC_HSI16, RCC_HSI48, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
Referenced by rcc_clock_setup_pll(), and rcc_wait_for_osc_ready().
rcc_osc_off()
void rcc_osc_off (enum rcc_osc osc)
Definition at line 74 of file rcc.c.
References RCC_CR, RCC_CR_HSEON, RCC_CR_HSI16ON, RCC_CR_MSION, RCC_CR_PLLON, RCC_CRRCR, RCC_CRRCR_HSI48ON, RCC_CSR, RCC_CSR_LSEON, RCC_CSR_LSION, RCC_HSE, RCC_HSI16, RCC_HSI48, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
Referenced by rcc_clock_setup_pll().
rcc_osc_on()
void rcc_osc_on (enum rcc_osc osc)
Definition at line 47 of file rcc.c.
References RCC_CR, RCC_CR_HSEON, RCC_CR_HSI16ON, RCC_CR_MSION, RCC_CR_PLLON, RCC_CRRCR, RCC_CRRCR_HSI48ON, RCC_CSR, RCC_CSR_LSEON, RCC_CSR_LSION, RCC_HSE, RCC_HSI16, RCC_HSI48, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
Referenced by rcc_clock_setup_pll().
rcc_osc_ready_int_clear()
void rcc_osc_ready_int_clear (enum rcc_osc osc)
RCC Clear the Oscillator Ready Interrupt Flag.
Clear the interrupt flag that was set when a clock oscillator became ready to use.
Parameters
[in] osc enum ::osc_t. Oscillator ID
Definition at line 110 of file rcc.c.
References RCC_CICR, RCC_CICR_HSERDYC, RCC_CICR_HSI16RDYC, RCC_CICR_HSI48RDYC, RCC_CICR_LSERDYC, RCC_CICR_LSIRDYC, RCC_CICR_MSIRDYC, RCC_CICR_PLLRDYC, RCC_HSE, RCC_HSI16, RCC_HSI48, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
rcc_osc_ready_int_disable()
void rcc_osc_ready_int_disable (enum rcc_osc osc)
RCC Disable the Oscillator Ready Interrupt.
Parameters
[in] osc enum ::osc_t. Oscillator ID
Definition at line 174 of file rcc.c.
References RCC_CIER, RCC_CIER_HSERDYIE, RCC_CIER_HSI16RDYIE, RCC_CIER_HSI48RDYIE, RCC_CIER_LSERDYIE, RCC_CIER_LSIRDYIE, RCC_CIER_MSIRDYIE, RCC_CIER_PLLRDYIE, RCC_HSE, RCC_HSI16, RCC_HSI48, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
rcc_osc_ready_int_enable()
void rcc_osc_ready_int_enable (enum rcc_osc osc)
RCC Enable the Oscillator Ready Interrupt.
Parameters
[in] osc enum ::osc_t. Oscillator ID
Definition at line 142 of file rcc.c.
References RCC_CIER, RCC_CIER_HSERDYIE, RCC_CIER_HSI16RDYIE, RCC_CIER_HSI48RDYIE, RCC_CIER_LSERDYIE, RCC_CIER_LSIRDYIE, RCC_CIER_MSIRDYIE, RCC_CIER_PLLRDYIE, RCC_HSE, RCC_HSI16, RCC_HSI48, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
rcc_osc_ready_int_flag()
int rcc_osc_ready_int_flag (enum rcc_osc osc)
RCC Read the Oscillator Ready Interrupt Flag.
Parameters
[in] osc enum ::osc_t. Oscillator ID
Returns
int. Boolean value for flag set.
Definition at line 207 of file rcc.c.
References RCC_CIFR, RCC_CIFR_HSERDYF, RCC_CIFR_HSI16RDYF, RCC_CIFR_HSI48RDYF, RCC_CIFR_LSERDYF, RCC_CIFR_LSIRDYF, RCC_CIFR_MSIRDYF, RCC_CIFR_PLLRDYF, RCC_HSE, RCC_HSI16, RCC_HSI48, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
rcc_set_hpre()
void rcc_set_hpre (uint32_t hpre)
RCC Set the AHB Prescale Factor.
Parameters
[in] hpre Unsigned int32. AHB prescale factor rcc_cfgr_ahbpre
Definition at line 375 of file rcc.c.
References RCC_CFGR, RCC_CFGR_HPRE_MASK, and RCC_CFGR_HPRE_SHIFT.
Referenced by rcc_clock_setup_pll().
rcc_set_hsi48_source_pll()
void rcc_set_hsi48_source_pll (void)
RCC Set HSI48 clock source to the PLL.
Definition at line 274 of file rcc.c.
References RCC_CCIPR, and RCC_CCIPR_HSI48SEL.
rcc_set_hsi48_source_rc48()
void rcc_set_hsi48_source_rc48 (void)
RCC Set HSI48 clock source to the RC48 (CRS)
Definition at line 266 of file rcc.c.
References RCC_CCIPR, and RCC_CCIPR_HSI48SEL.
rcc_set_pll_divider()
void rcc_set_pll_divider (uint32_t factor)
RCC Set the PLL Division Factor.
Note
This only has effect when the PLL is disabled.
Parameters
[in] mul Unsigned int32. PLL multiplication factor rcc_cfgr_pdf
Definition at line 332 of file rcc.c.
References RCC_CFGR, RCC_CFGR_PLLDIV_MASK, and RCC_CFGR_PLLDIV_SHIFT.
Referenced by rcc_clock_setup_pll().
rcc_set_pll_multiplier()
void rcc_set_pll_multiplier (uint32_t factor)
RCC Set the PLL Multiplication Factor.
Note
This only has effect when the PLL is disabled.
Parameters
[in] mul Unsigned int32. PLL multiplication factor rcc_cfgr_pmf
Definition at line 316 of file rcc.c.
References RCC_CFGR, RCC_CFGR_PLLMUL_MASK, and RCC_CFGR_PLLMUL_SHIFT.
Referenced by rcc_clock_setup_pll().
rcc_set_ppre1()
void rcc_set_ppre1 (uint32_t ppre)
RCC Set the APB1 Prescale Factor.
Note
The APB1 clock frequency must not exceed 32MHz.
Parameters
[in] ppre1 Unsigned int32. APB prescale factor rcc_cfgr_apb1pre
Definition at line 347 of file rcc.c.
References RCC_CFGR, RCC_CFGR_PPRE1_MASK, and RCC_CFGR_PPRE1_SHIFT.
Referenced by rcc_clock_setup_pll().
rcc_set_ppre2()
void rcc_set_ppre2 (uint32_t ppre)
RCC Set the APB2 Prescale Factor.
Note
The APB2 clock frequency must not exceed 32MHz.
Parameters
[in] ppre1 Unsigned int32. APB prescale factor rcc_cfgr_apb2pre
Definition at line 362 of file rcc.c.
References RCC_CFGR, RCC_CFGR_PPRE2_MASK, and RCC_CFGR_PPRE2_SHIFT.
Referenced by rcc_clock_setup_pll().
rcc_set_sysclk_source()
void rcc_set_sysclk_source (enum rcc_osc osc)
RCC Set the Source for the System Clock.
Parameters
[in] osc enum ::osc_t. Oscillator ID. Only HSE, HSI16, MSI and PLL have effect.
Definition at line 286 of file rcc.c.
References RCC_CFGR, RCC_CFGR_SW_HSE, RCC_CFGR_SW_HSI16, RCC_CFGR_SW_MASK, RCC_CFGR_SW_MSI, RCC_CFGR_SW_PLL, RCC_HSE, RCC_HSI16, RCC_HSI48, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
Referenced by rcc_clock_setup_pll().
rcc_wait_for_osc_ready()
void rcc_wait_for_osc_ready (enum rcc_osc osc)
Wait for Oscillator Ready.
Block until the hardware indicates that the Oscillator is ready.
Parameters
osc Oscillator ID
Definition at line 258 of file rcc.c.
References rcc_is_osc_ready().
Referenced by rcc_clock_setup_pll().
Variable Documentation
rcc_ahb_frequency
uint32_t rcc_ahb_frequency = 2097000
Definition at line 43 of file rcc.c.
Referenced by rcc_clock_setup_pll().
rcc_apb1_frequency
uint32_t rcc_apb1_frequency = 2097000
Definition at line 44 of file rcc.c.
Referenced by rcc_clock_setup_pll(), and usart_set_baudrate().
rcc_apb2_frequency
uint32_t rcc_apb2_frequency = 2097000
Definition at line 45 of file rcc.c.
Referenced by rcc_clock_setup_pll(), and usart_set_baudrate().