libopencm3: rtc.h File Reference
rtc.h File Reference
#include <libopencm3/stm32/common/rtc_common_l1f024.h>
Functions
void rtc_enable_wakeup_timer (void)
Enable the wakeup timer.
void rtc_disable_wakeup_timer (void)
Disable the wakeup timer.
void rtc_enable_wakeup_timer_interrupt (void)
Enable the wakeup timer interrupt.
void rtc_disable_wakeup_timer_interrupt (void)
Disable the wakeup timer interrupt.
Function Documentation
rtc_disable_wakeup_timer()
void rtc_disable_wakeup_timer (void)
Disable the wakeup timer.
Warning
You must unlock the registers before using this function
Definition at line 52 of file rtc.c.
References RTC_CR, RTC_CR_WUTE, and rtc_disable_wakeup_timer_interrupt().
rtc_disable_wakeup_timer_interrupt()
void rtc_disable_wakeup_timer_interrupt (void)
Disable the wakeup timer interrupt.
Warning
You must unlock the registers before using this function
Definition at line 87 of file rtc.c.
References EXTI22, exti_disable_request(), RTC_CR, and RTC_CR_WUTIE.
Referenced by rtc_disable_wakeup_timer().
rtc_enable_wakeup_timer()
void rtc_enable_wakeup_timer (void)
Enable the wakeup timer.
Warning
You must unlock the registers before using this function
Definition at line 41 of file rtc.c.
References RTC_CR, RTC_CR_OSEL_SHIFT, RTC_CR_OSEL_WAKEUP, RTC_CR_WUTE, and rtc_enable_wakeup_timer_interrupt().
rtc_enable_wakeup_timer_interrupt()
void rtc_enable_wakeup_timer_interrupt (void)
Enable the wakeup timer interrupt.
Warning
You must unlock the registers before using this function
Definition at line 63 of file rtc.c.
References EXTI22, exti_enable_request(), exti_set_trigger(), EXTI_TRIGGER_RISING, RTC_CR, and RTC_CR_WUTIE.
Referenced by rtc_enable_wakeup_timer().