libopencm3: FLASH Defines
FLASH Defines
STM32F0xx Defines
Defined Constants and Types for the STM32F0xx Flash memory
Modules
Option Byte Addresses
FLASH Wait States
Macros
#define FLASH_SR_EOP (1 << 5)
#define FLASH_SR_WRPRTERR (1 << 4)
#define FLASH_SR_PGERR (1 << 2)
#define FLASH_SR_BSY (1 << 0)
#define FLASH_CR_OBL_LAUNCH (1 << 13)
#define FLASH_OBR_DATA1_SHIFT 24
#define FLASH_OBR_DATA1 (0xFF << FLASH_OBR_DATA1_SHIFT)
#define FLASH_OBR_DATA0_SHIFT 16
#define FLASH_OBR_DATA0 (0xFF << FLASH_OBR_DATA0_SHIFT)
#define FLASH_OBR_BOOT_SEL (1 << 15)
#define FLASH_OBR_RAM_PARITY_CHECK (1 << 14)
#define FLASH_OBR_VDDA_MONITOR (1 << 13)
#define FLASH_OBR_NBOOT1 (1 << 12)
#define FLASH_OBR_NBOOT0 (1 << 11)
#define FLASH_OBR_NRST_STDBY (1 << 10)
#define FLASH_OBR_NRST_STOP (1 << 9)
#define FLASH_OBR_WDG_SW (1 << 8)
#define FLASH_OBR_RDPRT (3 << FLASH_OBR_RDPRT_SHIFT)
#define FLASH_OBR_RDPRT_L0 (0 << FLASH_OBR_RDPRT_SHIFT)
#define FLASH_OBR_RDPRT_L1 (1 << FLASH_OBR_RDPRT_SHIFT)
#define FLASH_OBR_RDPRT_L2 (3 << FLASH_OBR_RDPRT_SHIFT)
#define FLASH_RDP_L0 ((uint8_t)0xaa)
#define FLASH_RDP_L1 ((uint8_t)0xf0) /* any value */
#define FLASH_RDP_L2 ((uint8_t)0xcc)
#define FLASH_ACR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x00)
#define FLASH_KEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x04)
#define FLASH_OPTKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x08)
#define FLASH_SR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x0C)
#define FLASH_CR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x10)
#define FLASH_AR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x14)
#define FLASH_OBR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x1C)
#define FLASH_WRPR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x20)
#define FLASH_KEYR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x44)
#define FLASH_SR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x4C)
#define FLASH_CR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x50)
#define FLASH_AR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x54)
#define FLASH_OPTION_BYTE(i) MMIO16(INFO_BASE+0x0800 + (i)*2)
#define FLASH_ACR_LATENCY_SHIFT 0
#define FLASH_ACR_LATENCY 7
#define FLASH_ACR_PRFTBS (1 << 5)
#define FLASH_ACR_PRFTBE (1 << 4)
#define FLASH_SR_EOP (1 << 5)
#define FLASH_SR_WRPRTERR (1 << 4)
#define FLASH_SR_PGERR (1 << 2)
#define FLASH_SR_BSY (1 << 0)
#define FLASH_CR_EOPIE (1 << 12)
#define FLASH_CR_ERRIE (1 << 10)
#define FLASH_CR_OPTWRE (1 << 9)
#define FLASH_CR_LOCK (1 << 7)
#define FLASH_CR_STRT (1 << 6)
#define FLASH_CR_OPTER (1 << 5)
#define FLASH_CR_OPTPG (1 << 4)
#define FLASH_CR_MER (1 << 2)
#define FLASH_CR_PER (1 << 1)
#define FLASH_CR_PG (1 << 0)
#define FLASH_OBR_RDPRT_SHIFT 1
#define FLASH_OBR_OPTERR (1 << 0)
#define FLASH_KEYR_KEY1 ((uint32_t)0x45670123)
#define FLASH_KEYR_KEY2 ((uint32_t)0xcdef89ab)
#define FLASH_ACR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x00)
#define FLASH_PECR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x04)
#define FLASH_PDKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x08)
#define FLASH_PEKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x0C)
#define FLASH_PRGKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x10)
#define FLASH_OPTKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x14)
#define FLASH_SR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x18)
#define FLASH_OBR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x1c)
#define FLASH_WRPR1 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x20)
#define FLASH_WRPR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x80)
#define FLASH_ACR_RUNPD (1 << 4)
#define FLASH_ACR_SLEEPPD (1 << 3)
#define FLASH_ACR_PRFTEN (1 << 1)
#define FLASH_PECR_OBL_LAUNCH (1 << 18)
#define FLASH_PECR_ERRIE (1 << 17)
#define FLASH_PECR_EOPIE (1 << 16)
#define FLASH_PECR_PARALLBANK (1 << 15)
#define FLASH_PECR_FPRG (1 << 10)
#define FLASH_PECR_ERASE (1 << 9)
#define FLASH_PECR_FTDW (1 << 8)
#define FLASH_PECR_DATA (1 << 4)
#define FLASH_PECR_PROG (1 << 3)
#define FLASH_PECR_OPTLOCK (1 << 2)
#define FLASH_PECR_PRGLOCK (1 << 1)
#define FLASH_PECR_PELOCK (1 << 0)
#define FLASH_PDKEYR_PDKEY1 ((uint32_t)0x04152637)
#define FLASH_PDKEYR_PDKEY2 ((uint32_t)0xFAFBFCFD)
#define FLASH_PEKEYR_PEKEY1 ((uint32_t)0x89ABCDEF)
#define FLASH_PEKEYR_PEKEY2 ((uint32_t)0x02030405)
#define FLASH_PRGKEYR_PRGKEY1 ((uint32_t)0x8C9DAEBF)
#define FLASH_PRGKEYR_PRGKEY2 ((uint32_t)0x13141516)
#define FLASH_OPTKEYR_OPTKEY1 ((uint32_t)0xFBEAD9C8)
#define FLASH_OPTKEYR_OPTKEY2 ((uint32_t)0x24252627)
#define FLASH_SR_OPTVERR (1 << 11)
#define FLASH_SR_SIZEERR (1 << 10)
#define FLASH_SR_PGAERR (1 << 9)
#define FLASH_SR_WRPERR (1 << 8)
#define FLASH_SR_READY (1 << 3)
#define FLASH_SR_ENDHV (1 << 2)
#define FLASH_SR_EOP (1 << 1)
#define FLASH_SR_BSY (1 << 0)
#define FLASH_OBR_BFB2 (1 << 23)
#define FLASH_OBR_NRST_STDBY (1 << 22)
#define FLASH_OBR_NRST_STOP (1 << 21)
#define FLASH_OBR_IWDG_SW (1 << 20)
#define FLASH_OBR_BOR_OFF (0x0 << 16)
#define FLASH_OBR_BOR_LEVEL_1 (0x8 << 16)
#define FLASH_OBR_BOR_LEVEL_2 (0x9 << 16)
#define FLASH_OBR_BOR_LEVEL_3 (0xa << 16)
#define FLASH_OBR_BOR_LEVEL_4 (0xb << 16)
#define FLASH_OBR_BOR_LEVEL_5 (0xc << 16)
#define FLASH_OBR_RDPRT_LEVEL_0 (0xaa)
#define FLASH_OBR_RDPRT_LEVEL_1 (0x00)
#define FLASH_OBR_RDPRT_LEVEL_2 (0xcc)
Functions
void flash_prefetch_buffer_enable (void)
Enable the FLASH Prefetch Buffer.
void flash_prefetch_buffer_disable (void)
Disable the FLASH Prefetch Buffer.
void flash_clear_pgerr_flag (void)
Clear the Programming Error Status Flag.
void flash_clear_eop_flag (void)
Clear the End of Operation Status Flag.
void flash_clear_wrprterr_flag (void)
Clear the Write Protect Error Status Flag.
void flash_clear_bsy_flag (void)
Clear the Busy Status Flag.
void flash_clear_status_flags (void)
Clear All Status Flags.
uint32_t flash_get_status_flags (void)
Read All Status Flags.
void flash_wait_for_last_operation (void)
Wait until Last Operation has Ended.
void flash_program_word (uint32_t address, uint32_t data)
Program a 32 bit Word to FLASH.
void flash_program_half_word (uint32_t address, uint16_t data)
Program a Half Word to FLASH.
void flash_erase_page (uint32_t page_address)
Erase a Page of FLASH.
void flash_erase_all_pages (void)
Erase All FLASH.
void flash_erase_option_bytes (void)
Erase All Option Bytes.
void flash_program_option_bytes (uint32_t address, uint16_t data)
Program the Option Bytes.
void flash_prefetch_enable (void)
Enable the FLASH Prefetch Buffer.
void flash_prefetch_disable (void)
Disable the FLASH Prefetch Buffer.
void flash_unlock_pecr (void)
Unlock primary access to the flash control/erase block You must call this before using any of the low level routines yourself.
void flash_lock_pecr (void)
void flash_unlock_progmem (void)
Unlock program memory itself.
void flash_lock_progmem (void)
void flash_lock_option_bytes (void)
void eeprom_program_word (uint32_t address, uint32_t data)
Write a word to eeprom.
void eeprom_program_words (uint32_t address, uint32_t *data, int length_in_words)
Write a block of words to eeprom.
Detailed Description
Defined Constants and Types for the STM32F0xx Flash memory
Version
1.0.0
Author
© 2013 Frantisek Burian BuFra.nosp@m.n@se.nosp@m.znam..nosp@m.cz
Date
14 January 2014
LGPL License Terms libopencm3 License
Macro Definition Documentation
FLASH_ACR [1/2]
#define FLASH_ACR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x00)
Definition at line 34 of file flash_common_l01.h.
FLASH_ACR [2/2]
#define FLASH_ACR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x00)
Definition at line 40 of file flash_common_f01.h.
Referenced by flash_prefetch_buffer_disable(), flash_prefetch_buffer_enable(), flash_prefetch_disable(), flash_prefetch_enable(), and flash_set_ws().
FLASH_ACR_LATENCY
#define FLASH_ACR_LATENCY 7
Definition at line 61 of file flash_common_f01.h.
Referenced by flash_set_ws().
FLASH_ACR_LATENCY_SHIFT
#define FLASH_ACR_LATENCY_SHIFT 0
Definition at line 60 of file flash_common_f01.h.
FLASH_ACR_PRFTBE
#define FLASH_ACR_PRFTBE (1 << 4)
Definition at line 64 of file flash_common_f01.h.
Referenced by flash_prefetch_buffer_disable(), and flash_prefetch_buffer_enable().
FLASH_ACR_PRFTBS
#define FLASH_ACR_PRFTBS (1 << 5)
Definition at line 63 of file flash_common_f01.h.
FLASH_ACR_PRFTEN
#define FLASH_ACR_PRFTEN (1 << 1)
Definition at line 48 of file flash_common_l01.h.
Referenced by flash_prefetch_disable(), and flash_prefetch_enable().
FLASH_ACR_RUNPD
#define FLASH_ACR_RUNPD (1 << 4)
Definition at line 46 of file flash_common_l01.h.
FLASH_ACR_SLEEPPD
#define FLASH_ACR_SLEEPPD (1 << 3)
Definition at line 47 of file flash_common_l01.h.
FLASH_AR
#define FLASH_AR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x14)
Definition at line 45 of file flash_common_f01.h.
Referenced by flash_erase_page().
FLASH_AR2
#define FLASH_AR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x54)
Definition at line 52 of file flash_common_f01.h.
FLASH_CR
#define FLASH_CR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x10)
Definition at line 44 of file flash_common_f01.h.
Referenced by flash_erase_all_pages(), flash_erase_option_bytes(), flash_erase_page(), flash_lock(), flash_program_half_word(), flash_program_option_bytes(), and flash_unlock().
FLASH_CR2
#define FLASH_CR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x50)
Definition at line 51 of file flash_common_f01.h.
FLASH_CR_EOPIE
#define FLASH_CR_EOPIE (1 << 12)
Definition at line 75 of file flash_common_f01.h.
FLASH_CR_ERRIE
#define FLASH_CR_ERRIE (1 << 10)
Definition at line 76 of file flash_common_f01.h.
FLASH_CR_LOCK
#define FLASH_CR_LOCK (1 << 7)
Definition at line 78 of file flash_common_f01.h.
Referenced by flash_lock(), and flash_unlock().
FLASH_CR_MER
#define FLASH_CR_MER (1 << 2)
Definition at line 82 of file flash_common_f01.h.
Referenced by flash_erase_all_pages().
FLASH_CR_OBL_LAUNCH
#define FLASH_CR_OBL_LAUNCH (1 << 13)
Definition at line 78 of file flash.h.
FLASH_CR_OPTER
#define FLASH_CR_OPTER (1 << 5)
Definition at line 80 of file flash_common_f01.h.
Referenced by flash_erase_option_bytes().
FLASH_CR_OPTPG
#define FLASH_CR_OPTPG (1 << 4)
Definition at line 81 of file flash_common_f01.h.
Referenced by flash_program_option_bytes().
FLASH_CR_OPTWRE
#define FLASH_CR_OPTWRE (1 << 9)
Definition at line 77 of file flash_common_f01.h.
Referenced by flash_erase_option_bytes(), and flash_program_option_bytes().
FLASH_CR_PER
#define FLASH_CR_PER (1 << 1)
Definition at line 83 of file flash_common_f01.h.
Referenced by flash_erase_page().
FLASH_CR_PG
#define FLASH_CR_PG (1 << 0)
Definition at line 84 of file flash_common_f01.h.
Referenced by flash_program_half_word().
FLASH_CR_STRT
#define FLASH_CR_STRT (1 << 6)
Definition at line 79 of file flash_common_f01.h.
Referenced by flash_erase_all_pages(), flash_erase_option_bytes(), and flash_erase_page().
FLASH_KEYR
#define FLASH_KEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x04)
Definition at line 41 of file flash_common_f01.h.
Referenced by flash_unlock().
FLASH_KEYR2
#define FLASH_KEYR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x44)
Definition at line 49 of file flash_common_f01.h.
FLASH_KEYR_KEY1
#define FLASH_KEYR_KEY1 ((uint32_t)0x45670123)
Definition at line 93 of file flash_common_f01.h.
Referenced by flash_unlock(), and flash_unlock_option_bytes().
FLASH_KEYR_KEY2
#define FLASH_KEYR_KEY2 ((uint32_t)0xcdef89ab)
Definition at line 94 of file flash_common_f01.h.
Referenced by flash_unlock(), and flash_unlock_option_bytes().
FLASH_OBR [1/2]
#define FLASH_OBR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x1c)
Definition at line 41 of file flash_common_l01.h.
FLASH_OBR [2/2]
#define FLASH_OBR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x1C)
Definition at line 46 of file flash_common_f01.h.
FLASH_OBR_BFB2
#define FLASH_OBR_BFB2 (1 << 23)
Definition at line 97 of file flash_common_l01.h.
FLASH_OBR_BOOT_SEL
#define FLASH_OBR_BOOT_SEL (1 << 15)
Definition at line 87 of file flash.h.
FLASH_OBR_BOR_LEVEL_1
#define FLASH_OBR_BOR_LEVEL_1 (0x8 << 16)
Definition at line 102 of file flash_common_l01.h.
FLASH_OBR_BOR_LEVEL_2
#define FLASH_OBR_BOR_LEVEL_2 (0x9 << 16)
Definition at line 103 of file flash_common_l01.h.
FLASH_OBR_BOR_LEVEL_3
#define FLASH_OBR_BOR_LEVEL_3 (0xa << 16)
Definition at line 104 of file flash_common_l01.h.
FLASH_OBR_BOR_LEVEL_4
#define FLASH_OBR_BOR_LEVEL_4 (0xb << 16)
Definition at line 105 of file flash_common_l01.h.
FLASH_OBR_BOR_LEVEL_5
#define FLASH_OBR_BOR_LEVEL_5 (0xc << 16)
Definition at line 106 of file flash_common_l01.h.
FLASH_OBR_BOR_OFF
#define FLASH_OBR_BOR_OFF (0x0 << 16)
Definition at line 101 of file flash_common_l01.h.
FLASH_OBR_DATA0
#define FLASH_OBR_DATA0 (0xFF << FLASH_OBR_DATA0_SHIFT)
Definition at line 85 of file flash.h.
FLASH_OBR_DATA0_SHIFT
#define FLASH_OBR_DATA0_SHIFT 16
Definition at line 84 of file flash.h.
FLASH_OBR_DATA1
#define FLASH_OBR_DATA1 (0xFF << FLASH_OBR_DATA1_SHIFT)
Definition at line 83 of file flash.h.
FLASH_OBR_DATA1_SHIFT
#define FLASH_OBR_DATA1_SHIFT 24
Definition at line 82 of file flash.h.
FLASH_OBR_IWDG_SW
#define FLASH_OBR_IWDG_SW (1 << 20)
Definition at line 100 of file flash_common_l01.h.
FLASH_OBR_NBOOT0
#define FLASH_OBR_NBOOT0 (1 << 11)
Definition at line 91 of file flash.h.
FLASH_OBR_NBOOT1
#define FLASH_OBR_NBOOT1 (1 << 12)
Definition at line 90 of file flash.h.
FLASH_OBR_NRST_STDBY [1/2]
#define FLASH_OBR_NRST_STDBY (1 << 10)
Definition at line 92 of file flash.h.
FLASH_OBR_NRST_STDBY [2/2]
#define FLASH_OBR_NRST_STDBY (1 << 22)
Definition at line 98 of file flash_common_l01.h.
FLASH_OBR_NRST_STOP [1/2]
#define FLASH_OBR_NRST_STOP (1 << 9)
Definition at line 93 of file flash.h.
FLASH_OBR_NRST_STOP [2/2]
#define FLASH_OBR_NRST_STOP (1 << 21)
Definition at line 99 of file flash_common_l01.h.
FLASH_OBR_OPTERR
#define FLASH_OBR_OPTERR (1 << 0)
Definition at line 89 of file flash_common_f01.h.
FLASH_OBR_RAM_PARITY_CHECK
#define FLASH_OBR_RAM_PARITY_CHECK (1 << 14)
Definition at line 88 of file flash.h.
FLASH_OBR_RDPRT
#define FLASH_OBR_RDPRT (3 << FLASH_OBR_RDPRT_SHIFT)
Definition at line 95 of file flash.h.
FLASH_OBR_RDPRT_L0
#define FLASH_OBR_RDPRT_L0 (0 << FLASH_OBR_RDPRT_SHIFT)
Definition at line 96 of file flash.h.
FLASH_OBR_RDPRT_L1
#define FLASH_OBR_RDPRT_L1 (1 << FLASH_OBR_RDPRT_SHIFT)
Definition at line 97 of file flash.h.
FLASH_OBR_RDPRT_L2
#define FLASH_OBR_RDPRT_L2 (3 << FLASH_OBR_RDPRT_SHIFT)
Definition at line 98 of file flash.h.
FLASH_OBR_RDPRT_LEVEL_0
#define FLASH_OBR_RDPRT_LEVEL_0 (0xaa)
Definition at line 107 of file flash_common_l01.h.
FLASH_OBR_RDPRT_LEVEL_1
#define FLASH_OBR_RDPRT_LEVEL_1 (0x00)
Definition at line 108 of file flash_common_l01.h.
FLASH_OBR_RDPRT_LEVEL_2
#define FLASH_OBR_RDPRT_LEVEL_2 (0xcc)
Definition at line 109 of file flash_common_l01.h.
FLASH_OBR_RDPRT_SHIFT
#define FLASH_OBR_RDPRT_SHIFT 1
Definition at line 88 of file flash_common_f01.h.
FLASH_OBR_VDDA_MONITOR
#define FLASH_OBR_VDDA_MONITOR (1 << 13)
Definition at line 89 of file flash.h.
FLASH_OBR_WDG_SW
#define FLASH_OBR_WDG_SW (1 << 8)
Definition at line 94 of file flash.h.
FLASH_OPTION_BYTE
#define FLASH_OPTION_BYTE (i) MMIO16(INFO_BASE+0x0800 + (i)*2)
Definition at line 56 of file flash_common_f01.h.
FLASH_OPTKEYR [1/2]
#define FLASH_OPTKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x14)
Definition at line 39 of file flash_common_l01.h.
FLASH_OPTKEYR [2/2]
#define FLASH_OPTKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x08)
Definition at line 42 of file flash_common_f01.h.
Referenced by flash_unlock_option_bytes().
FLASH_OPTKEYR_OPTKEY1
#define FLASH_OPTKEYR_OPTKEY1 ((uint32_t)0xFBEAD9C8)
Definition at line 83 of file flash_common_l01.h.
Referenced by flash_unlock_option_bytes().
FLASH_OPTKEYR_OPTKEY2
#define FLASH_OPTKEYR_OPTKEY2 ((uint32_t)0x24252627)
Definition at line 84 of file flash_common_l01.h.
Referenced by flash_unlock_option_bytes().
FLASH_PDKEYR
#define FLASH_PDKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x08)
Definition at line 36 of file flash_common_l01.h.
FLASH_PDKEYR_PDKEY1
#define FLASH_PDKEYR_PDKEY1 ((uint32_t)0x04152637)
Definition at line 71 of file flash_common_l01.h.
FLASH_PDKEYR_PDKEY2
#define FLASH_PDKEYR_PDKEY2 ((uint32_t)0xFAFBFCFD)
Definition at line 72 of file flash_common_l01.h.
FLASH_PECR
#define FLASH_PECR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x04)
Definition at line 35 of file flash_common_l01.h.
Referenced by eeprom_program_word(), eeprom_program_words(), flash_lock_option_bytes(), flash_lock_pecr(), and flash_lock_progmem().
FLASH_PECR_DATA
#define FLASH_PECR_DATA (1 << 4)
Definition at line 64 of file flash_common_l01.h.
FLASH_PECR_EOPIE
#define FLASH_PECR_EOPIE (1 << 16)
Definition at line 59 of file flash_common_l01.h.
FLASH_PECR_ERASE
#define FLASH_PECR_ERASE (1 << 9)
Definition at line 62 of file flash_common_l01.h.
FLASH_PECR_ERRIE
#define FLASH_PECR_ERRIE (1 << 17)
Definition at line 58 of file flash_common_l01.h.
FLASH_PECR_FPRG
#define FLASH_PECR_FPRG (1 << 10)
Definition at line 61 of file flash_common_l01.h.
FLASH_PECR_FTDW
#define FLASH_PECR_FTDW (1 << 8)
Definition at line 63 of file flash_common_l01.h.
Referenced by eeprom_program_word(), and eeprom_program_words().
FLASH_PECR_OBL_LAUNCH
#define FLASH_PECR_OBL_LAUNCH (1 << 18)
Definition at line 57 of file flash_common_l01.h.
FLASH_PECR_OPTLOCK
#define FLASH_PECR_OPTLOCK (1 << 2)
Definition at line 66 of file flash_common_l01.h.
Referenced by flash_lock_option_bytes().
FLASH_PECR_PARALLBANK
#define FLASH_PECR_PARALLBANK (1 << 15)
Definition at line 60 of file flash_common_l01.h.
FLASH_PECR_PELOCK
#define FLASH_PECR_PELOCK (1 << 0)
Definition at line 68 of file flash_common_l01.h.
Referenced by flash_lock_pecr().
FLASH_PECR_PRGLOCK
#define FLASH_PECR_PRGLOCK (1 << 1)
Definition at line 67 of file flash_common_l01.h.
Referenced by flash_lock_progmem().
FLASH_PECR_PROG
#define FLASH_PECR_PROG (1 << 3)
Definition at line 65 of file flash_common_l01.h.
FLASH_PEKEYR
#define FLASH_PEKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x0C)
Definition at line 37 of file flash_common_l01.h.
Referenced by flash_unlock_pecr().
FLASH_PEKEYR_PEKEY1
#define FLASH_PEKEYR_PEKEY1 ((uint32_t)0x89ABCDEF)
Definition at line 75 of file flash_common_l01.h.
Referenced by flash_unlock_pecr().
FLASH_PEKEYR_PEKEY2
#define FLASH_PEKEYR_PEKEY2 ((uint32_t)0x02030405)
Definition at line 76 of file flash_common_l01.h.
Referenced by flash_unlock_pecr().
FLASH_PRGKEYR
#define FLASH_PRGKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x10)
Definition at line 38 of file flash_common_l01.h.
Referenced by flash_unlock_progmem().
FLASH_PRGKEYR_PRGKEY1
#define FLASH_PRGKEYR_PRGKEY1 ((uint32_t)0x8C9DAEBF)
Definition at line 79 of file flash_common_l01.h.
Referenced by flash_unlock_progmem().
FLASH_PRGKEYR_PRGKEY2
#define FLASH_PRGKEYR_PRGKEY2 ((uint32_t)0x13141516)
Definition at line 80 of file flash_common_l01.h.
Referenced by flash_unlock_progmem().
FLASH_RDP_L0
#define FLASH_RDP_L0 ((uint8_t)0xaa)
Definition at line 105 of file flash.h.
FLASH_RDP_L1
#define FLASH_RDP_L1 ((uint8_t)0xf0) /* any value */
Definition at line 106 of file flash.h.
FLASH_RDP_L2
#define FLASH_RDP_L2 ((uint8_t)0xcc)
Definition at line 107 of file flash.h.
FLASH_SR [1/2]
#define FLASH_SR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x18)
Definition at line 40 of file flash_common_l01.h.
FLASH_SR [2/2]
#define FLASH_SR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x0C)
Definition at line 43 of file flash_common_f01.h.
Referenced by eeprom_program_words(), flash_clear_bsy_flag(), flash_clear_eop_flag(), flash_clear_pgerr_flag(), flash_clear_wrprterr_flag(), and flash_get_status_flags().
FLASH_SR2
#define FLASH_SR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x4C)
Definition at line 50 of file flash_common_f01.h.
FLASH_SR_BSY [1/3]
#define FLASH_SR_BSY (1 << 0)
Definition at line 71 of file flash_common_f01.h.
FLASH_SR_BSY [2/3]
#define FLASH_SR_BSY (1 << 0)
Definition at line 74 of file flash.h.
Referenced by eeprom_program_words(), flash_clear_bsy_flag(), flash_get_status_flags(), and flash_wait_for_last_operation().
FLASH_SR_BSY [3/3]
#define FLASH_SR_BSY (1 << 0)
Definition at line 94 of file flash_common_l01.h.
FLASH_SR_ENDHV
#define FLASH_SR_ENDHV (1 << 2)
Definition at line 92 of file flash_common_l01.h.
FLASH_SR_EOP [1/3]
#define FLASH_SR_EOP (1 << 5)
Definition at line 68 of file flash_common_f01.h.
FLASH_SR_EOP [2/3]
#define FLASH_SR_EOP (1 << 5)
Definition at line 71 of file flash.h.
Referenced by flash_clear_eop_flag(), and flash_get_status_flags().
FLASH_SR_EOP [3/3]
#define FLASH_SR_EOP (1 << 1)
Definition at line 93 of file flash_common_l01.h.
FLASH_SR_OPTVERR
#define FLASH_SR_OPTVERR (1 << 11)
Definition at line 87 of file flash_common_l01.h.
FLASH_SR_PGAERR
#define FLASH_SR_PGAERR (1 << 9)
Definition at line 89 of file flash_common_l01.h.
FLASH_SR_PGERR [1/2]
#define FLASH_SR_PGERR (1 << 2)
Definition at line 70 of file flash_common_f01.h.
FLASH_SR_PGERR [2/2]
#define FLASH_SR_PGERR (1 << 2)
Definition at line 73 of file flash.h.
Referenced by flash_clear_pgerr_flag(), and flash_get_status_flags().
FLASH_SR_READY
#define FLASH_SR_READY (1 << 3)
Definition at line 91 of file flash_common_l01.h.
FLASH_SR_SIZEERR
#define FLASH_SR_SIZEERR (1 << 10)
Definition at line 88 of file flash_common_l01.h.
FLASH_SR_WRPERR
#define FLASH_SR_WRPERR (1 << 8)
Definition at line 90 of file flash_common_l01.h.
FLASH_SR_WRPRTERR [1/2]
#define FLASH_SR_WRPRTERR (1 << 4)
Definition at line 69 of file flash_common_f01.h.
FLASH_SR_WRPRTERR [2/2]
#define FLASH_SR_WRPRTERR (1 << 4)
Definition at line 72 of file flash.h.
Referenced by flash_clear_wrprterr_flag(), and flash_get_status_flags().
FLASH_WRPR
#define FLASH_WRPR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x20)
Definition at line 47 of file flash_common_f01.h.
FLASH_WRPR1
#define FLASH_WRPR1 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x20)
Definition at line 42 of file flash_common_l01.h.
FLASH_WRPR2
#define FLASH_WRPR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x80)
Definition at line 43 of file flash_common_l01.h.
Function Documentation
eeprom_program_word()
void eeprom_program_word (uint32_t address, uint32_t data)
Write a word to eeprom.
Parameters
address assumed to be in the eeprom space, no checking
data word to write
Definition at line 158 of file flash_common_l01.c.
References flash_lock_pecr(), FLASH_PECR, FLASH_PECR_FTDW, and flash_unlock_pecr().
eeprom_program_words()
void eeprom_program_words (uint32_t address, uint32_t * data, int length_in_words)
Write a block of words to eeprom.
Writes a block of words to EEPROM at the requested address, erasing if necessary, and locking afterwards. Only wordwise writing is safe for writing any value
Parameters
[in] address must point to EEPROM space, no checking!
[in] data pointer to data to write
[in] length_in_words size of of data in WORDS!
Definition at line 177 of file flash_common_l01.c.
References flash_lock_pecr(), FLASH_PECR, FLASH_PECR_FTDW, FLASH_SR, FLASH_SR_BSY, and flash_unlock_pecr().
flash_clear_bsy_flag()
void flash_clear_bsy_flag (void)
Clear the Busy Status Flag.
Definition at line 135 of file flash_common_f01.c.
References FLASH_SR, and FLASH_SR_BSY.
Referenced by flash_clear_status_flags().
flash_clear_eop_flag()
void flash_clear_eop_flag (void)
Clear the End of Operation Status Flag.
Definition at line 115 of file flash_common_f01.c.
References FLASH_SR, and FLASH_SR_EOP.
Referenced by flash_clear_status_flags().
flash_clear_pgerr_flag()
void flash_clear_pgerr_flag (void)
Clear the Programming Error Status Flag.
Definition at line 105 of file flash_common_f01.c.
References FLASH_SR, and FLASH_SR_PGERR.
Referenced by flash_clear_status_flags().
flash_clear_status_flags()
void flash_clear_status_flags (void)
Clear All Status Flags.
Program error, end of operation, write protect error, busy.
Definition at line 59 of file flash.c.
References flash_clear_bsy_flag(), flash_clear_eop_flag(), flash_clear_pgerr_flag(), and flash_clear_wrprterr_flag().
flash_clear_wrprterr_flag()
void flash_clear_wrprterr_flag (void)
Clear the Write Protect Error Status Flag.
Definition at line 125 of file flash_common_f01.c.
References FLASH_SR, and FLASH_SR_WRPRTERR.
Referenced by flash_clear_status_flags().
flash_erase_all_pages()
void flash_erase_all_pages (void)
Erase All FLASH.
This performs all operations necessary to erase all user pages in the FLASH memory. The information block is unaffected.
Definition at line 144 of file flash.c.
References FLASH_CR, FLASH_CR_MER, FLASH_CR_STRT, and flash_wait_for_last_operation().
flash_erase_option_bytes()
void flash_erase_option_bytes (void)
Erase All Option Bytes.
This performs all operations necessary to erase the option bytes. These must first be fully erased before attempting to program them, therefore it is recommended to check these after an erase attempt.
Definition at line 193 of file flash_common_f01.c.
References FLASH_CR, FLASH_CR_OPTER, FLASH_CR_OPTWRE, FLASH_CR_STRT, flash_unlock_option_bytes(), and flash_wait_for_last_operation().
flash_erase_page()
void flash_erase_page (uint32_t page_address)
Erase a Page of FLASH.
This performs all operations necessary to erase a page in FLASH memory. The page should be checked to ensure that it was properly erased. A page must first be fully erased before attempting to program it.
Note that the page sizes differ between devices. See the reference manual or the FLASH programming manual for details.
Parameters
[in] page_address Full address of flash page to be erased.
Definition at line 124 of file flash.c.
References FLASH_AR, FLASH_CR, FLASH_CR_PER, FLASH_CR_STRT, and flash_wait_for_last_operation().
flash_get_status_flags()
uint32_t flash_get_status_flags (void)
Read All Status Flags.
The programming error, end of operation, write protect error and busy flags are returned in the order of appearance in the status register.
Returns
uint32_t. bit 0: busy, bit 2: programming error, bit 4: write protect error, bit 5: end of operation.
Definition at line 77 of file flash.c.
References FLASH_SR, FLASH_SR_BSY, FLASH_SR_EOP, FLASH_SR_PGERR, and FLASH_SR_WRPRTERR.
Referenced by flash_wait_for_last_operation().
flash_lock_option_bytes()
void flash_lock_option_bytes (void)
Definition at line 128 of file flash_common_l01.c.
References FLASH_PECR, and FLASH_PECR_OPTLOCK.
Referenced by flash_lock().
flash_lock_pecr()
void flash_lock_pecr (void)
Definition at line 94 of file flash_common_l01.c.
References FLASH_PECR, and FLASH_PECR_PELOCK.
Referenced by eeprom_program_word(), eeprom_program_words(), and flash_lock().
flash_lock_progmem()
void flash_lock_progmem (void)
Definition at line 111 of file flash_common_l01.c.
References FLASH_PECR, and FLASH_PECR_PRGLOCK.
Referenced by flash_lock().
flash_prefetch_buffer_disable()
void flash_prefetch_buffer_disable (void)
Disable the FLASH Prefetch Buffer.
Note carefully the clock restrictions under which the prefetch buffer may be set to disabled. See the reference manual for details.
Definition at line 52 of file flash_common_f01.c.
References FLASH_ACR, and FLASH_ACR_PRFTBE.
flash_prefetch_buffer_enable()
void flash_prefetch_buffer_enable (void)
Enable the FLASH Prefetch Buffer.
This buffer is used for instruction fetches and is enabled by default after reset.
Note carefully the clock restrictions under which the prefetch buffer may be enabled or disabled. Changes are normally made while the clock is running in the power-on low frequency mode before being set to a higher speed mode. See the reference manual for details.
Definition at line 40 of file flash_common_f01.c.
References FLASH_ACR, and FLASH_ACR_PRFTBE.
Referenced by rcc_clock_setup_in_hse_8mhz_out_48mhz(), rcc_clock_setup_in_hsi48_out_48mhz(), and rcc_clock_setup_in_hsi_out_48mhz().
flash_prefetch_disable()
void flash_prefetch_disable (void)
Disable the FLASH Prefetch Buffer.
Note carefully the restrictions under which the prefetch buffer may be set to disabled. See the reference and programming manuals for details.
Definition at line 55 of file flash_common_l01.c.
References FLASH_ACR, and FLASH_ACR_PRFTEN.
flash_prefetch_enable()
void flash_prefetch_enable (void)
Enable the FLASH Prefetch Buffer.
This buffer is used for instruction fetches and is enabled by default after reset.
Note carefully the restrictions under which the prefetch buffer may be enabled or disabled. Prefetch is only available when 64-bit access is enabled.
Definition at line 43 of file flash_common_l01.c.
References FLASH_ACR, and FLASH_ACR_PRFTEN.
flash_program_half_word()
void flash_program_half_word (uint32_t address, uint16_t data)
Program a Half Word to FLASH.
This performs all operations necessary to program a 16 bit word to FLASH memory. The program error flag should be checked separately for the event that memory was not properly erased.
Status bit polling is used to detect end of operation.
Parameters
[in] address Full address of flash half word to be programmed.
[in] data half word to write
Definition at line 98 of file flash.c.
References FLASH_CR, FLASH_CR_PG, and flash_wait_for_last_operation().
Referenced by flash_program_word().
flash_program_option_bytes()
void flash_program_option_bytes (uint32_t address, uint16_t data)
Program the Option Bytes.
This performs all operations necessary to program the option bytes. The write protect error flag should be checked separately for the event that an option byte had not been properly erased before calling this function.
Only the lower 8 bits of the data is significant.
Parameters
[in] address Address of option byte from Option Byte Addresses.
[in] data value to write
Definition at line 220 of file flash_common_f01.c.
References FLASH_CR, FLASH_CR_OPTPG, FLASH_CR_OPTWRE, flash_unlock_option_bytes(), and flash_wait_for_last_operation().
flash_program_word()
void flash_program_word (uint32_t address, uint32_t data)
Program a 32 bit Word to FLASH.
This performs all operations necessary to program a 32 bit word to FLASH memory. The program error flag should be checked separately for the event that memory was not properly erased.
Status bit polling is used to detect end of operation.
Parameters
[in] address Full address of flash word to be programmed.
[in] data word to write
Definition at line 165 of file flash_common_f01.c.
References flash_program_half_word().
flash_unlock_pecr()
void flash_unlock_pecr (void)
Unlock primary access to the flash control/erase block You must call this before using any of the low level routines yourself.
See also
flash_unlock
Definition at line 88 of file flash_common_l01.c.
References FLASH_PEKEYR, FLASH_PEKEYR_PEKEY1, and FLASH_PEKEYR_PEKEY2.
Referenced by eeprom_program_word(), eeprom_program_words(), and flash_unlock().
flash_unlock_progmem()
void flash_unlock_progmem (void)
Unlock program memory itself.
Writes the magic sequence to unlock the program memory you must have already unlocked access to this register!
See also
flash_unlock_pecr
Definition at line 105 of file flash_common_l01.c.
References FLASH_PRGKEYR, FLASH_PRGKEYR_PRGKEY1, and FLASH_PRGKEYR_PRGKEY2.
Referenced by flash_unlock().
flash_wait_for_last_operation()
void flash_wait_for_last_operation (void)
Wait until Last Operation has Ended.
This loops indefinitely until an operation (write or erase) has completed by testing the busy flag.
Definition at line 147 of file flash_common_f01.c.
References flash_get_status_flags(), and FLASH_SR_BSY.
Referenced by flash_erase_all_pages(), flash_erase_option_bytes(), flash_erase_page(), flash_program_half_word(), and flash_program_option_bytes().